port=53
user=nobody
group=nogroup
interface=virbr-hpsbx
listen-address=198.18.0.1
bind-interfaces
no-dhcp-interface=virbr-hpsbx
no-hosts
no-resolv
server=9.9.9.9
server=1.1.1.1
domain-needed
bogus-priv
stop-dns-rebind
cache-size=0
log-queries=extra
log-facility=/var/log/honeypot-sandbox/dns/queries.log
