// Canarytokens — deployed decoy tokens (dashboard-canarytokens-v1), plus
// minting new ones against the self-hosted Canarytokens platform and
// downloading their artifacts.
import { createFileRoute } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/react-start'
import { useEffect, useState } from 'react'
import { StoreListPage, str, when, type StorePage, type StoreRow } from '../components/StoreList'
import type { Column } from '../components/Investigate'

type TokenType = {
  token_type: string
  label: string
  description: string
  requires_upload: boolean
  supports_snippet: boolean
}

const fetchPage = createServerFn({ method: 'GET' })
  .inputValidator((input: { offset: number }) => input)
  .handler(async ({ data }): Promise<StorePage | null> => {
    const { serviceJSON } = await import('../lib/backend.server')
    return serviceJSON<StorePage>(`/api/v1/store/canarytokens?offset=${data.offset}&size=25`)
  })

const fetchTypes = createServerFn({ method: 'GET' }).handler(async (): Promise<TokenType[] | null> => {
  const { serviceJSON } = await import('../lib/backend.server')
  return serviceJSON<TokenType[]>('/api/v1/canarytokens/types')
})

const createToken = createServerFn({ method: 'POST' })
  .inputValidator(
    (input: {
      token_type: string
      memo: string
      include_text_snippet?: boolean
      text_snippet?: string
      file_base64?: string
      file_name?: string
      file_content_type?: string
    }) => input,
  )
  .handler(async ({ data }): Promise<{ ok: boolean; error?: string }> => {
    const { serviceFetch } = await import('../lib/backend.server')
    const { getSessionUser } = await import('../lib/auth')
    const user = await getSessionUser()
    const response = await serviceFetch('/api/v1/canarytokens', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ ...data, created_by: user?.username ?? '' }),
    })
    if (response.ok) return { ok: true }
    return { ok: false, error: await response.text() }
  })

function MintForm({ onCreated }: { onCreated: () => void }) {
  const [types, setTypes] = useState<TokenType[]>([])
  const [tokenType, setTokenType] = useState('adobe_pdf')
  const [memo, setMemo] = useState('')
  const [snippet, setSnippet] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')

  useEffect(() => {
    let cancelled = false
    fetchTypes().then((result) => {
      if (!cancelled && result) setTypes(result)
    })
    return () => {
      cancelled = true
    }
  }, [])

  const selected = types.find((entry) => entry.token_type === tokenType)

  return (
    <div className="card wide">
      <h2>Mint a new token</h2>
      <p className="note">
        The artifact is generated by the self-hosted Canarytokens platform over the internal tunnel; fired events land in the
        pipeline like any other sensor.
      </p>
      <form
        className="filters"
        onSubmit={async (event) => {
          event.preventDefault()
          if (busy) return
          setBusy(true)
          setMessage('')
          try {
            let filePayload: { file_base64?: string; file_name?: string; file_content_type?: string } = {}
            if (selected?.requires_upload) {
              if (!file) {
                setMessage('This token type needs an image upload.')
                return
              }
              const buffer = await file.arrayBuffer()
              let binary = ''
              for (const byte of new Uint8Array(buffer)) binary += String.fromCharCode(byte)
              filePayload = { file_base64: btoa(binary), file_name: file.name, file_content_type: file.type }
            }
            const result = await createToken({
              data: {
                token_type: tokenType,
                memo,
                include_text_snippet: Boolean(selected?.supports_snippet && snippet.trim()),
                text_snippet: snippet,
                ...filePayload,
              },
            })
            if (result.ok) {
              setMemo('')
              setSnippet('')
              setFile(null)
              setMessage('Token minted.')
              onCreated()
            } else {
              setMessage(result.error || 'Creation failed.')
            }
          } finally {
            setBusy(false)
          }
        }}
      >
        <select className="input" aria-label="Token type" value={tokenType} onChange={(event) => setTokenType(event.target.value)}>
          {types.map((entry) => (
            <option key={entry.token_type} value={entry.token_type}>
              {entry.label}
            </option>
          ))}
        </select>
        <input
          className="input"
          type="text"
          required
          placeholder="memo — where will this token live?"
          value={memo}
          onChange={(event) => setMemo(event.target.value)}
          aria-label="Memo"
        />
        {selected?.supports_snippet ? (
          <input
            className="input"
            type="text"
            placeholder="visible text snippet (optional)"
            value={snippet}
            onChange={(event) => setSnippet(event.target.value)}
            aria-label="Text snippet"
          />
        ) : null}
        {selected?.requires_upload ? (
          <input
            className="input"
            type="file"
            accept="image/*"
            onChange={(event) => setFile(event.target.files?.[0] ?? null)}
            aria-label="Image upload"
          />
        ) : null}
        <button className="btn btn-secondary btn-sm" type="submit" disabled={busy || !memo.trim()}>
          {busy ? 'Minting…' : 'Mint token'}
        </button>
        {message ? <span className="note">{message}</span> : null}
      </form>
      {selected ? <p className="note">{selected.description}</p> : null}
    </div>
  )
}

const COLUMNS: Column<StoreRow>[] = [
  { header: 'created', render: (row) => when(str(row, 'created_at')) },
  { header: 'type', render: (row) => <span className="badge badge--muted">{str(row, 'token_type')}</span> },
  { header: 'memo', className: 'v', render: (row) => str(row, 'memo') },
  { header: 'token url', className: 'v', render: (row) => <code>{str(row, 'token_url')}</code> },
  { header: 'hostname', detail: true, render: (row) => str(row, 'hostname') },
  { header: 'created by', detail: true, render: (row) => str(row, 'created_by') },
  { header: 'id', detail: true, render: (row) => str(row, 'id') },
  {
    header: 'artifact',
    render: (row) =>
      str(row, 'token_type') === 'web_image' ? (
        ''
      ) : (
        <a
          className="lnk"
          href={`/api/canarytoken/${encodeURIComponent(str(row, 'id'))}/download`}
          onClick={(event) => event.stopPropagation()}
        >
          download →
        </a>
      ),
  },
]

export const Route = createFileRoute('/canarytokens')({ component: Page })

function Page() {
  // Remount the list after a mint so the new token appears immediately.
  const [generation, setGeneration] = useState(0)
  return (
    <>
      <MintForm onCreated={() => setGeneration((current) => current + 1)} />
      <StoreListPage
        key={generation}
        fetchPage={fetchPage}
        label="Tools"
        title="Canarytokens"
        subtitle="Deployed decoy tokens — documents, URLs and hostnames that phone home the moment an attacker touches them."
        columns={COLUMNS}
        rowKey={(row, index) => `${str(row, 'id')}-${index}`}
        inspectorTitle="Token details"
        chipNoun="tokens"
      />
    </>
  )
}
