// Canarytokens — deployed decoy tokens (dashboard-canarytokens-v1), plus
// minting new ones against the self-hosted Canarytokens platform and
// downloading their artifacts.
import { createFileRoute } from '@tanstack/react-router'
import { createServerFn } from '@tanstack/react-start'
import { useCallback, useEffect, useRef, useState } from 'react'
import { StoreListPage, str, when, type StorePage, type StoreRow } from '../components/StoreList'
import { InvestigateHeader, type Column } from '../components/Investigate'
import { Tabs, TabPanel } from '../components/Tabs'
import { pathString, type JsonRecord } from '../lib/json'
import { copyWithFlash } from '../lib/flash'
import { useLiveInterval } from '../lib/live'
import { formatTimestamp } from '../lib/time'
import { countryName } from '../lib/country'

type TokenType = {
  token_type: string
  label: string
  description: string
  requires_upload: boolean
  supports_snippet: boolean
}

const fetchPage = createServerFn({ method: 'GET' })
  .inputValidator((input: { offset: number }) => input)
  .handler(async ({ data }): Promise<StorePage | null> => {
    const { serviceJSON } = await import('../lib/backend.server')
    return serviceJSON<StorePage>(`/api/v1/store/canarytokens?offset=${data.offset}&size=25`)
  })

/** One fired-token event off /api/v1/events — the slice of EventRow this
 * tab renders (the full record rides along for honeypot.token_type/
 * manage_url, which the flat row doesn't carry). */
type FiredRow = {
  time: string
  src_ip: string
  country: string
  detail: string
  record: JsonRecord
}

type FiredPage = { total: number; rows: FiredRow[] }

const fetchFired = createServerFn({ method: 'GET' }).handler(async (): Promise<FiredPage | null> => {
  const { serviceJSON } = await import('../lib/backend.server')
  // since=365d: tokens fire rarely — the events endpoint's 10d default
  // would hide older fires the old page still showed (hp-canarytokens.js
  // loadReports read the whole in-memory event cache).
  return serviceJSON<FiredPage>('/api/v1/events?sensor=canarytokens&size=50&since=365d')
})

const fetchTypes = createServerFn({ method: 'GET' }).handler(async (): Promise<TokenType[] | null> => {
  const { serviceJSON } = await import('../lib/backend.server')
  return serviceJSON<TokenType[]>('/api/v1/canarytokens/types')
})

const createToken = createServerFn({ method: 'POST' })
  .inputValidator(
    (input: {
      token_type: string
      memo: string
      include_text_snippet?: boolean
      text_snippet?: string
      file_base64?: string
      file_name?: string
      file_content_type?: string
    }) => input,
  )
  .handler(async ({ data }): Promise<{ ok: boolean; error?: string }> => {
    const { serviceFetch } = await import('../lib/backend.server')
    const { getSessionUser } = await import('../lib/auth')
    const user = await getSessionUser()
    const response = await serviceFetch('/api/v1/canarytokens', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ ...data, created_by: user?.username ?? '' }),
    })
    if (response.ok) return { ok: true }
    return { ok: false, error: await response.text() }
  })

function MintForm({ onCreated, presetType, formRef }: { onCreated: () => void; presetType?: string; formRef?: React.RefObject<HTMLDivElement | null> }) {
  const [types, setTypes] = useState<TokenType[]>([])
  const [tokenType, setTokenType] = useState(presetType || 'adobe_pdf')
  const [memo, setMemo] = useState('')
  const [snippet, setSnippet] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')

  useEffect(() => {
    let cancelled = false
    fetchTypes().then((result) => {
      if (!cancelled && result) setTypes(result)
    })
    return () => {
      cancelled = true
    }
  }, [])

  // #1575's template-gallery empty state (below) preselects a type by
  // jumping in here — never on first render (that's the useState above),
  // only on a later pick, so the operator's own dropdown choice isn't
  // fought if they'd already started filling the form out.
  useEffect(() => {
    if (presetType) setTokenType(presetType)
    // eslint-disable-next-line react-hooks/exhaustive-deps -- fire on presetType change only
  }, [presetType])

  const selected = types.find((entry) => entry.token_type === tokenType)

  return (
    <div className="card wide" ref={formRef}>
      <h2>Mint a new token</h2>
      <p className="note">
        The artifact is generated by the self-hosted Canarytokens platform over the internal tunnel; fired events land in the
        pipeline like any other sensor.
      </p>
      <form
        className="filters"
        onSubmit={async (event) => {
          event.preventDefault()
          if (busy) return
          setBusy(true)
          setMessage('')
          try {
            let filePayload: { file_base64?: string; file_name?: string; file_content_type?: string } = {}
            if (selected?.requires_upload) {
              if (!file) {
                setMessage('This token type needs an image upload.')
                return
              }
              const buffer = await file.arrayBuffer()
              let binary = ''
              for (const byte of new Uint8Array(buffer)) binary += String.fromCharCode(byte)
              filePayload = { file_base64: btoa(binary), file_name: file.name, file_content_type: file.type }
            }
            const result = await createToken({
              data: {
                token_type: tokenType,
                memo,
                include_text_snippet: Boolean(selected?.supports_snippet && snippet.trim()),
                text_snippet: snippet,
                ...filePayload,
              },
            })
            if (result.ok) {
              setMemo('')
              setSnippet('')
              setFile(null)
              setMessage('Token minted.')
              onCreated()
            } else {
              setMessage(result.error || 'Creation failed.')
            }
          } finally {
            setBusy(false)
          }
        }}
      >
        <select className="form-input" aria-label="Token type" value={tokenType} onChange={(event) => setTokenType(event.target.value)}>
          {types.map((entry) => (
            <option key={entry.token_type} value={entry.token_type}>
              {entry.label}
            </option>
          ))}
        </select>
        <input
          className="form-input"
          type="text"
          required
          placeholder="memo — where will this token live?"
          value={memo}
          onChange={(event) => setMemo(event.target.value)}
          aria-label="Memo"
        />
        {selected?.supports_snippet ? (
          <input
            className="form-input"
            type="text"
            placeholder="visible text snippet (optional)"
            value={snippet}
            onChange={(event) => setSnippet(event.target.value)}
            aria-label="Text snippet"
          />
        ) : null}
        {selected?.requires_upload ? (
          <input
            className="form-input"
            type="file"
            accept="image/*"
            onChange={(event) => setFile(event.target.files?.[0] ?? null)}
            aria-label="Image upload"
          />
        ) : null}
        <button className="btn btn-secondary btn-sm" type="submit" disabled={busy || !memo.trim()}>
          {busy ? 'Minting…' : 'Mint token'}
        </button>
        {message ? <span className="note">{message}</span> : null}
      </form>
      {selected ? <p className="note">{selected.description}</p> : null}
    </div>
  )
}

const COLUMNS: Column<StoreRow>[] = [
  { header: 'created', render: (row) => when(str(row, 'created_at')) },
  { header: 'type', render: (row) => <span className="badge badge--muted">{str(row, 'token_type')}</span> },
  { header: 'memo', className: 'v', primary: true, render: (row) => str(row, 'memo') || <span className="text-muted">(no memo)</span> },
  {
    header: 'token url',
    className: 'v',
    // #1859: a token URL has no spaces and no break opportunities, so it ran
    // straight past the card edge. `overflow-wrap: anywhere` lets it break
    // mid-string, which is what a URL needs -- it stops deciding the card's
    // width instead of being allowed to.
    //
    // A token URL exists to be pasted somewhere, so it also gets a copy
    // control rather than leaving the operator to select wrapped text
    // accurately.
    render: (row) => {
      const url = str(row, 'token_url')
      if (!url) return '—'
      return (
        <span className="hp-token-url">
          <code>{url}</code>
          <button
            type="button"
            className="btn btn-ghost btn-sm"
            title="copy the token URL"
            onClick={(event) => {
              event.stopPropagation()
              copyWithFlash(url, 'token URL')
            }}
          >
            copy
          </button>
        </span>
      )
    },
  },
  { header: 'hostname', detail: true, render: (row) => str(row, 'hostname') },
  { header: 'created by', detail: true, render: (row) => str(row, 'created_by') },
  { header: 'id', detail: true, render: (row) => str(row, 'id') },
  {
    header: 'artifact',
    render: (row) =>
      str(row, 'token_type') === 'web_image' ? (
        ''
      ) : (
        <a
          className="lnk"
          href={`/api/canarytoken/${encodeURIComponent(str(row, 'id'))}/download`}
          onClick={(event) => event.stopPropagation()}
        >
          download →
        </a>
      ),
  },
]

// Fired-tokens tab (canarytokens.html:114-133 / hp-canarytokens.js
// renderFiredRow+loadReports): every time a planted token was opened,
// scanned or triggered — newest first, with the platform's manage link.
function FiredTokens() {
  const [page, setPage] = useState<FiredPage | null>(null)
  const [error, setError] = useState('')
  const load = useCallback(async () => {
    try {
      const result = await fetchFired()
      if (result) {
        setPage(result)
        setError('')
      } else {
        setError('Fired-token history unavailable.')
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Fired-token history unavailable.')
    }
  }, [])
  // #1973: the shared tick replaces the hand-rolled guarded interval —
  // same visible-tab + LIVE-paused guards, resume refetch included.
  // Leading, because unlike the routes above this tab owns its own
  // initial fetch; there is no loader to cover first paint.
  useLiveInterval(load, 60_000, { leading: true })
  const rows = page?.rows ?? null
  return (
    <div className="card wide">
      <div className="card__header">
        <div>
          <h2>Fired tokens</h2>
          <p className="card__meta">Every time a planted token was opened, scanned, or triggered — newest first.</p>
        </div>
        <div className="hp-head-actions">
          <button className="btn btn-ghost btn-sm" type="button" onClick={() => void load()}>
            Refresh
          </button>
        </div>
      </div>
      <div className="card__scroll">
        <table className="data-table">
          <thead>
            <tr>
              <th>Time</th>
              <th>Source IP</th>
              <th>Country</th>
              <th>Token type</th>
              <th>Detail</th>
              <th>Manage</th>
            </tr>
          </thead>
          <tbody>
            {rows === null ? (
              <tr>
                <td colSpan={6}>
                  <span className="skeleton-line" aria-hidden="true" />
                </td>
              </tr>
            ) : (
              rows.map((row, index) => {
                const manageURL = pathString(row.record, 'honeypot', 'manage_url')
                const tokenType =
                  pathString(row.record, 'honeypot', 'token_type') || pathString(row.record, 'honeypot', 'channel')
                return (
                  <tr key={`${row.time}-${index}`}>
                    <td>{formatTimestamp(row.time)}</td>
                    <td className="mono">
                      {row.src_ip ? (
                        <a href={`/investigate/ip/${encodeURIComponent(row.src_ip)}`}>{row.src_ip}</a>
                      ) : (
                        '—'
                      )}
                    </td>
                    <td>{row.country ? <span className="badge badge--info" title={countryName(row.country)}>{row.country}</span> : '—'}</td>
                    <td>{tokenType || '—'}</td>
                    <td className="v">{row.detail || pathString(row.record, 'honeypot', 'memo') || '—'}</td>
                    <td>
                      {manageURL ? (
                        <a className="btn btn-ghost btn-sm" href={manageURL} target="_blank" rel="noopener noreferrer">
                          Manage token
                        </a>
                      ) : (
                        '—'
                      )}
                    </td>
                  </tr>
                )
              })
            )}
          </tbody>
        </table>
      </div>
      {rows !== null && rows.length === 0 ? (
        <p className="empty" role="status">
          No token has fired yet.
        </p>
      ) : null}
      {error ? (
        <p className="card__meta" role="alert">
          {error}
        </p>
      ) : null}
    </div>
  )
}

// #1575's empty-state gallery (canarytokens.html:53-77): jump straight
// into Create with a common type preselected, instead of making a
// first-time operator pick blind from the full type dropdown.
const TEMPLATES: { type: string; title: string; desc: string; chip: string; icon: React.ReactNode }[] = [
  {
    type: 'ms_word',
    title: 'Fake .docx',
    desc: "A real Word doc that phones home the moment it's opened.",
    chip: 'Document',
    icon: (
      <>
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
        <polyline points="14 2 14 8 20 8" />
      </>
    ),
  },
  {
    type: 'qr_code',
    title: 'QR code',
    desc: 'A PNG QR code that fires when scanned and opened.',
    chip: 'Image',
    icon: (
      <>
        <rect x="3" y="3" width="7" height="7" />
        <rect x="14" y="3" width="7" height="7" />
        <rect x="3" y="14" width="7" height="7" />
        <line x1="14" y1="14" x2="14" y2="21" />
        <line x1="21" y1="14" x2="21" y2="21" />
        <line x1="17.5" y1="14" x2="17.5" y2="17.5" />
        <line x1="17.5" y1="17.5" x2="21" y2="17.5" />
      </>
    ),
  },
  {
    type: 'windows_dir',
    title: 'Windows folder',
    desc: 'Fires the moment the folder opens in Explorer.',
    chip: 'Folder',
    icon: <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" />,
  },
  {
    type: 'web_image',
    title: 'Web bug image',
    desc: 'An embeddable image that fires when it loads anywhere.',
    chip: 'Embed',
    icon: (
      <>
        <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
        <circle cx="8.5" cy="8.5" r="1.5" />
        <polyline points="21 15 16 10 5 21" />
      </>
    ),
  },
]

function TokenGallery({ onPick }: { onPick: (type: string) => void }) {
  return (
    <div className="card wide">
      <div className="empty-state" role="status" aria-live="polite">
        <div>
          <div className="empty-state__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <circle cx="12" cy="12" r="9" />
              <circle cx="12" cy="12" r="4" />
              <line x1="12" y1="3" x2="12" y2="8" />
              <line x1="12" y1="16" x2="12" y2="21" />
              <line x1="3" y1="12" x2="8" y2="12" />
              <line x1="16" y1="12" x2="21" y2="12" />
            </svg>
          </div>
          <div className="empty-state__title">No canarytokens yet</div>
          <p className="empty-state__hint">
            Plant tokens outside the honeypot and track everything that fires — nothing here re-fires a token.
          </p>
          <hr className="empty-state__divider" />
          <div className="template-gallery" role="group" aria-label="Common token types">
            {TEMPLATES.map((template) => (
              <button
                key={template.type}
                type="button"
                className="template-card"
                onClick={() => onPick(template.type)}
              >
                <span className="template-card__icon" aria-hidden="true">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    {template.icon}
                  </svg>
                </span>
                <span className="template-card__title">{template.title}</span>
                <span className="template-card__desc">{template.desc}</span>
                <span className="chip">{template.chip}</span>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/canarytokens')({ component: Page })

function Page() {
  // Remount the list after a mint so the new token appears immediately.
  const [generation, setGeneration] = useState(0)
  const [tab, setTab] = useState('tokens')
  const [presetType, setPresetType] = useState<string | undefined>(undefined)
  const formRef = useRef<HTMLDivElement>(null)
  const pickTemplate = useCallback((type: string) => {
    setPresetType(type)
    formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }, [])
  return (
    <>
      <Tabs
        tabs={[
          { id: 'tokens', label: 'Tokens' },
          { id: 'fired', label: 'Fired tokens' },
        ]}
        active={tab}
        onSelect={setTab}
        label="Canarytokens sections"
        idPrefix="ct"
      />
      <TabPanel id="tokens" active={tab} idPrefix="ct" className="dashboard-panel">
        <MintForm onCreated={() => setGeneration((current) => current + 1)} presetType={presetType} formRef={formRef} />
        <StoreListPage
          key={generation}
          fetchPage={fetchPage}
          label="Tools"
          title="Canarytokens"
          subtitle="Deployed decoy tokens — documents, URLs and hostnames that phone home the moment an attacker touches them."
          columns={COLUMNS}
          rowKey={(row, index) => `${str(row, 'id')}-${index}`}
          emptyReplacement={<TokenGallery onPick={pickTemplate} />}
          inspectorTitle="Token details"
          chipNoun="tokens"
          layout="cards"
        />
      </TabPanel>
      <TabPanel id="fired" active={tab} idPrefix="ct" className="dashboard-panel">
        <InvestigateHeader
          label="Tools"
          title="Canarytokens"
          subtitle="What's fired — every planted token that phoned home, wherever it was opened."
        />
        <FiredTokens />
      </TabPanel>
    </>
  )
}
