#!/usr/bin/env python3
"""Generate the dashboard's embedded equirectangular Natural Earth map.

The output uses the exact 1000x450 longitude/latitude projection used for
GeoLite2 attack markers in main.go. Runtime networking is not required.
"""

from __future__ import annotations

import html
import json
import pathlib
import urllib.request


SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/"
    "geojson/ne_110m_admin_0_countries.geojson"
)
OUTPUT = pathlib.Path(__file__).with_name("worldmap_generated.go")


def project(point: list[float]) -> tuple[float, float]:
    lon, lat = point[:2]
    return (lon + 180.0) / 360.0 * 1000.0, (90.0 - lat) / 180.0 * 450.0


def ring_path(ring: list[list[float]]) -> str:
    if not ring:
        return ""
    projected = [project(point) for point in ring]
    commands = [f"M{projected[0][0]:.1f},{projected[0][1]:.1f}"]
    commands.extend(f"L{x:.1f},{y:.1f}" for x, y in projected[1:])
    commands.append("Z")
    return "".join(commands)


def geometry_path(geometry: dict) -> str:
    coordinates = geometry.get("coordinates", [])
    if geometry.get("type") == "Polygon":
        polygons = [coordinates]
    elif geometry.get("type") == "MultiPolygon":
        polygons = coordinates
    else:
        return ""
    return "".join(ring_path(ring) for polygon in polygons for ring in polygon)


def main() -> None:
    request = urllib.request.Request(SOURCE, headers={"User-Agent": "xore-honeypot-map-generator"})
    with urllib.request.urlopen(request, timeout=60) as response:
        collection = json.load(response)

    paths: list[str] = []
    labels: list[str] = []
    for feature in collection["features"]:
        properties = feature.get("properties", {})
        name = str(properties.get("NAME") or properties.get("ADMIN") or "Unknown")
        iso = str(properties.get("ISO_A2") or "")
        path = geometry_path(feature.get("geometry") or {})
        if path:
            paths.append(
                f'<path class="land country" data-country="{html.escape(iso)}" '
                f'd="{path}"><title>{html.escape(name)}</title></path>'
            )

        rank = int(properties.get("LABELRANK") or 9)
        lon = properties.get("LABEL_X")
        lat = properties.get("LABEL_Y")
        if rank <= 6 and isinstance(lon, (int, float)) and isinstance(lat, (int, float)):
            x, y = project([float(lon), float(lat)])
            labels.append(
                f'<text class="country-label rank-{rank}" x="{x:.1f}" y="{y:.1f}">'
                f'{html.escape(name)}</text>'
            )

    svg = (
        '<g class="countries" aria-label="country boundaries">'
        + "".join(paths)
        + '</g><g class="country-labels" aria-label="country names">'
        + "".join(labels)
        + "</g>"
    )
    source = (
        "// Code generated by generate_worldmap.py; DO NOT EDIT.\n"
        "// Natural Earth 1:110m Admin 0 Countries, public domain.\n"
        "package main\n\n"
        "const worldMapSVG = `"
        + svg
        + "`\n"
    )
    OUTPUT.write_text(source, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT.name}: {len(paths)} countries, {len(labels)} labels")


if __name__ == "__main__":
    main()
