package main

// llm_analysis_search.go — #151: semantic search over llm-analysis session
// summaries, the query-time half of the feature (the write side --
// llm-worker embedding session summaries into a versioned dense_vector
// field -- shipped separately in llm-worker/worker.py).
//
// Operator decision: the dashboard calls Ollama directly to embed the
// user's free-text query at request time, rather than proxying through
// llm-worker (a batch loop with no request-serving API) or inventing a new
// service. Same local-only-endpoint contract llm-worker's own
// endpoint_is_local() already enforces for OLLAMA_URL, so this can never be
// pointed at an external inference API. Bounded and best-effort: if Ollama
// is unreachable or misconfigured, search reports itself unavailable
// rather than breaking the page or falling back to a non-semantic result
// set a caller might mistake for a real match.
import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// ollamaEndpointIsLocal mirrors llm-worker/worker.py's endpoint_is_local():
// plain http, no credentials/query/path, and a hostname that is either a
// known in-stack service name, localhost, or a private/loopback/link-local
// address. Config-time validation only -- DNS can still resolve "ollama" to
// whatever the honeypot-llm Docker network assigns it, same trust boundary
// ELASTICSEARCH_URL already carries.
func ollamaEndpointIsLocal(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil {
		return false
	}
	if u.Scheme != "http" || u.User != nil || u.RawQuery != "" || (u.Path != "" && u.Path != "/") {
		return false
	}
	host := strings.ToLower(u.Hostname())
	if host == "ollama" || host == "localhost" {
		return true
	}
	ip := net.ParseIP(host)
	if ip == nil {
		return false
	}
	if ip.IsLoopback() || ip.IsLinkLocalUnicast() || ip.IsPrivate() {
		return true
	}
	return false
}

const (
	embeddingSearchTimeout = 15 * time.Second
	embeddingSearchK       = 10
	embeddingSearchCands   = 100
)

// embedQueryText asks Ollama for a query embedding, bounded by
// embeddingSearchTimeout. Mirrors llm-worker/worker.py's OllamaClient.embed()
// request/response shape exactly (POST /api/embed, {"embeddings":[[...]]}),
// so a vector this produces is directly comparable to what llm-worker wrote
// into llm-analysis documents -- same model, same request shape.
func embedQueryText(ollamaURL, model, text string) ([]float64, error) {
	body, err := json.Marshal(map[string]any{"model": model, "input": text})
	if err != nil {
		return nil, err
	}
	client := &http.Client{Timeout: embeddingSearchTimeout}
	req, err := http.NewRequest(http.MethodPost, strings.TrimRight(ollamaURL, "/")+"/api/embed", bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("ollama embed: %s: %s", resp.Status, strings.TrimSpace(string(raw)))
	}
	var payload struct {
		Embeddings [][]float64 `json:"embeddings"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return nil, err
	}
	if len(payload.Embeddings) != 1 || len(payload.Embeddings[0]) == 0 {
		return nil, fmt.Errorf("ollama embed: response did not carry exactly one non-empty vector")
	}
	return payload.Embeddings[0], nil
}

// llmAnalysisSearchHit is one kNN result: the same llmAnalysisDoc shape
// every other llm-analysis view already renders, plus the similarity score
// this specific query produced -- provenance the issue's own acceptance
// criteria require ("search results expose provenance and similarity
// score").
type llmAnalysisSearchHit struct {
	llmAnalysisDoc
	Score float64 `json:"score"`
}

// serveLLMAnalysisSearch implements GET /api/llm/analysis/search?q=...:
// embeds the query via Ollama, runs a bounded Elasticsearch kNN search over
// llm-analysis's embedding field, and returns the ranked results. Every
// result is already labelled AI-generated by llmAnalysisDoc.AIGenerated()
// like any other llm-analysis view.
func (s *store) serveLLMAnalysisSearch(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	q := strings.TrimSpace(r.URL.Query().Get("q"))
	if q == "" {
		json.NewEncoder(w).Encode(map[string]any{"available": true, "hits": []llmAnalysisSearchHit{}})
		return
	}
	if s.es == nil || s.ollamaURL == "" {
		json.NewEncoder(w).Encode(map[string]any{"available": false, "reason": "semantic search is not configured on this deployment"})
		return
	}
	// Bounded: a single free-text query, never the attacker-controlled
	// session transcripts themselves -- those only ever reach a model
	// through llm-worker's own sanitize_text(), a boundary this endpoint
	// does not cross.
	if len(q) > 512 {
		q = q[:512]
	}
	vector, err := embedQueryText(s.ollamaURL, s.embeddingModel, q)
	if err != nil {
		json.NewEncoder(w).Encode(map[string]any{"available": false, "reason": "embedding the query failed: " + err.Error()})
		return
	}
	limit, _ := strconv.Atoi(r.URL.Query().Get("limit"))
	if limit <= 0 || limit > embeddingSearchK {
		limit = embeddingSearchK
	}
	queryBody, err := json.Marshal(map[string]any{
		"knn": map[string]any{
			"field":          "embedding",
			"query_vector":   vector,
			"k":              limit,
			"num_candidates": embeddingSearchCands,
			"filter":         map[string]any{"term": map[string]any{"doc_type": "session"}},
		},
		"_source": true,
	})
	if err != nil {
		json.NewEncoder(w).Encode(map[string]any{"available": false, "reason": err.Error()})
		return
	}
	raw, err := s.es.searchBody("/llm-analysis/_search", queryBody)
	if err != nil {
		json.NewEncoder(w).Encode(map[string]any{"available": false, "reason": err.Error()})
		return
	}
	var resp struct {
		Hits struct {
			Hits []struct {
				Score  float64         `json:"_score"`
				Source json.RawMessage `json:"_source"`
			} `json:"hits"`
		} `json:"hits"`
	}
	if err := json.Unmarshal(raw, &resp); err != nil {
		json.NewEncoder(w).Encode(map[string]any{"available": false, "reason": err.Error()})
		return
	}
	hits := make([]llmAnalysisSearchHit, 0, len(resp.Hits.Hits))
	for _, h := range resp.Hits.Hits {
		var doc llmAnalysisDoc
		if json.Unmarshal(h.Source, &doc) != nil {
			continue
		}
		hits = append(hits, llmAnalysisSearchHit{llmAnalysisDoc: doc, Score: h.Score})
	}
	json.NewEncoder(w).Encode(map[string]any{"available": true, "hits": hits})
}
