//! The parameter shapes the /api contract pins, as named types.
//!
//! # Why a type per shape rather than a schema literal at each use
//!
//! #3325's contract is generated by `utoipa` now, which means the schemas
//! reach the document through the types the handler annotations name. Most
//! of what the old hand-written table pinned was a handful of shapes
//! repeated: a non-negative integer, a page size, a hex subject id, an
//! enum of store names. Giving each one a name here means the shape is
//! written down once and the annotations say which shape they mean, and a
//! reviewer changing the page-size bound changes it in one file.
//!
//! Every one of these is a *contract* claim, not a validation: nothing in
//! the crate enforces them, and the `document_is_well_formed` test in
//! `openapi.rs` only checks that the document is loadable. A schema here
//! that the handler does not honour is a contract that lies, which is the
//! one failure mode the old table's module doc called out. They are
//! transcribed from the handler structs the parameters mirror, and each
//! type's doc comment names the struct it tracks so a reader can check it
//! in one jump.
//!
//! Each one is emitted *inline* into the operation that uses it -- hence
//! `inline(...)` at every use site -- so the document needs no
//! `components/schemas` section to be self-contained.

use serde_json::json;
use utoipa::__dev::ComposeSchema;
use utoipa::openapi::RefOr;
use utoipa::openapi::schema::{Object, Schema, SchemaType};
use utoipa::ToSchema;

/// Builds a schema object from a JSON literal, so what the document carries
/// is exactly the literal and nothing this module forgot to say.
fn literal(raw: serde_json::Value) -> Schema {
    // An empty object is the free-form schema: one that constrains nothing,
    // which accepts any JSON value. utoipa models that as
    // `SchemaType::AnyValue`, the one type it omits on the way out -- and
    // the one shape that cannot come back in through `Object`, which
    // requires its `type`.
    if raw.as_object().is_some_and(serde_json::Map::is_empty) {
        return Schema::Object(Object::with_type(SchemaType::AnyValue));
    }
    let object: Object =
        serde_json::from_value(raw).expect("every literal in this module is a valid schema");
    Schema::Object(object)
}

/// Implements the three traits utoipa needs for a hand-written schema: the
/// object itself, its composition under generics, and the registration hook
/// (which stays empty because every use site asks for the schema inline).
macro_rules! contract_schema {
    ($(#[$meta:meta])* $name:ident = $schema:expr) => {
        $(#[$meta])*
        pub struct $name;

        impl ComposeSchema for $name {
            fn compose(_: Vec<RefOr<Schema>>) -> RefOr<Schema> {
                RefOr::T(literal($schema))
            }
        }

        impl ToSchema for $name {}
    };
}

contract_schema!(
    /// `u64` page offsets. Traces `stores::PageQuery::offset` and the same
    /// field on `events::EventsQuery` and `aggregates::PageQuery`.
    NonNegativeInt = json!({"type": "integer", "format": "int64", "minimum": 0})
);

contract_schema!(
    /// A count that cannot be zero. `stores::StoreQuery::size`,
    /// `aggregates::PageQuery::size`, `llm_search`'s `limit`, and the
    /// `limit` on `/api/v1/llm-search`.
    PositiveInt = json!({"type": "integer", "format": "int64", "minimum": 1})
);

contract_schema!(
    /// The page size the store family clamps to 100 in the handler.
    /// `stores::StoreQuery::size` and `events::EventsQuery::size`.
    PageSize = json!({"type": "integer", "format": "int64", "minimum": 1, "maximum": 100})
);

contract_schema!(
    /// `/api/v1/audit`'s `limit`, which the handler clamps to `[1, 500]`.
    /// `audit::AuditQuery::limit`.
    AuditLimit = json!({"type": "integer", "minimum": 1, "maximum": 500})
);

contract_schema!(
    /// `/api/v1/services/{name}/logs`'s `lines`, defaulted to 200 by the
    /// handler. `services_control::LogsQuery::lines`.
    LogLines = json!({"type": "integer", "format": "int32", "minimum": 1})
);

contract_schema!(
    /// A count with no upper bound the contract states. The `limit` on
    /// `/api/v1/sensors/{sensor}/events`, which the handler clamps but
    /// `sensors::EventsQuery` does not bound.
    PositiveCount = json!({"type": "integer", "minimum": 1})
);

contract_schema!(
    /// The `sensor` path segment. `sensors::EventsQuery`/`OverviewQuery`
    /// reject an empty value or one over 128 characters.
    SensorName = json!({"type": "string", "maxLength": 128})
);

contract_schema!(
    /// A 32- or 64-character hex payload id. `payload_detail` rejects
    /// anything else with a 400.
    PayloadHash = json!({"type": "string", "pattern": "^[0-9a-fA-F]{32}([0-9a-fA-F]{32})?$"})
);

contract_schema!(
    /// The `{sha}` segment on the Ghidra, RevDeck, CAPE and GitHub-analysis
    /// routes: 8 to 64 hex characters.
    AnalysisSha = json!({"type": "string", "pattern": "^[0-9a-fA-F]{8,64}$"})
);

contract_schema!(
    /// The attacker-cluster kinds. `zeek_proxy_attribution`'s cluster
    /// resolver, and the same set the `/api/v1/clusters` store buckets by.
    ClusterKind = json!({"type": "string", "enum": ["fingerprint", "payload", "asn", "provider"]})
);

contract_schema!(
    /// The artifact families `/api/v1/artifacts/{kind}/...` exposes. The
    /// analyser adapter answers anything else with a 404.
    ArtifactKind = json!({"type": "string", "enum": ["ghidra", "sandbox"]})
);

contract_schema!(
    /// The lifecycle actions `/api/v1/services/{name}/{action}` accepts.
    ServiceAction = json!({"type": "string", "enum": ["start", "stop", "restart"]})
);

contract_schema!(
    /// The child-run actions on
    /// `/api/v1/workbench/runs/{id}/children/{analyzer_id}/{action}`.
    ChildAction = json!({"type": "string", "enum": ["cancel", "retry"]})
);

contract_schema!(
    /// The settings sections `PUT /api/v1/config/{section}` replaces.
    ConfigSection = json!({"type": "string", "enum": ["honeypot", "behavior", "report-presets"]})
);

/// The allowlisted store names, mirroring `stores.rs`'s `store_config`
/// match. A copy rather than a reference because the contract is a
/// document, not a view of the binary -- but it is a copy with teeth:
/// anything outside this list is a 404 at runtime, so widening the
/// contract's enum without widening the allowlist would advertise a
/// route that cannot work. `the_store_enum_matches_the_handside_allowlist`
/// in `openapi.rs` is what keeps the copy honest.
pub const STORE_NAMES: &[&str] = &[
    "agent-campaigns",
    "auth-events",
    "canarytokens",
    "cape",
    "dead-letters",
    "generated-reports",
    "ghidra-runs",
    "github-analysis",
    "intelligence",
    "llm-analysis",
    "ml-anomalies",
    "problem-reports",
    "report-definitions",
    "revdeck",
    "sandbox-runs",
    "static-analysis",
    "workbench-runs",
    "yara",
];

contract_schema!(
    /// The `{name}` segment on `/api/v1/store/{name}` -- see
    /// [`STORE_NAMES`], which this is generated from so the two cannot
    /// disagree.
    StoreName = json!({"type": "string", "enum": STORE_NAMES})
);
