"""#3329 attribution check: real hits from main's history, and near-misses that must pass."""
from __future__ import annotations

import importlib.util
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SCRIPT = Path(__file__).resolve().parents[1] / "check-ai-attribution.py"
_spec = importlib.util.spec_from_file_location("check_ai_attribution", SCRIPT)
caa = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(caa)

# Shapes actually found on main between 2026-08-01 and 2026-09-26.
HITS = [
    "fix: x\n\nCo-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>",
    "fix: x\n\nCo-authored-by: Claude Fable 5 <noreply@anthropic.com>",
    "fix: x\n\nco-authored-by: Claude <noreply@anthropic.com>",
    "fix: x\n\nClaude-Session: https://claude.ai/code/session_01JuThL8fCegxTxDudzWiZ7a",
    "## Summary\n\nstuff\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)",
    "Generated by Codex",
    "Co-authored-by: GitHub Copilot <copilot@users.noreply.github.com>",
    "Co-authored-by: openai-codex <codex@openai.com>",
    "see https://chatgpt.com/codex/tasks/task_e_123",
]
NEAR_MISSES = [
    "feat(theme): add the claude palette to the picker",
    "research: evaluate the Claude API for summaries",
    "The daily summary was generated by qwen3:14b at temperature 0.",
    "ci: call api.anthropic.com only from the llm tier",
    "Co-authored-by: Jane Doe <jane@example.com>",
    "docs: compare Copilot and Cursor licensing for the team",
    "llm-worker scores gemini and deepseek cells in the benchmark",
]


class FindingsTests(unittest.TestCase):
    def test_every_attribution_shape_is_caught(self):
        for text in HITS:
            with self.subTest(text=text[:50]):
                self.assertTrue(caa.findings(text), text)

    def test_mentions_are_not_attribution(self):
        for text in NEAR_MISSES:
            with self.subTest(text=text[:50]):
                self.assertEqual(caa.findings(text), [], text)

    def test_finding_quotes_the_offending_line(self):
        [hit, *_] = caa.findings("fix: x\n\nbody\nCo-Authored-By: Claude Sonnet 5 <noreply@anthropic.com>\n")
        self.assertIn("Co-Authored-By: Claude Sonnet 5", hit)


class PullRequestTests(unittest.TestCase):
    def event(self, **pr):
        base = {"number": 7, "title": "fix: thing", "body": "clean", "user": {"login": "Xore"}}
        base.update(pr)
        return {"pull_request": base, "repository": {"full_name": "o/r"}}

    def run_main(self, event, commits):
        with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as fh:
            json.dump(event, fh)
        env = {"GITHUB_EVENT_PATH": fh.name, "GITHUB_TOKEN": "t"}
        try:
            with mock.patch.dict(os.environ, env), mock.patch.object(caa, "_api", return_value=commits):
                return caa.main([])
        finally:
            os.unlink(fh.name)

    def test_clean_pr_passes(self):
        self.assertEqual(self.run_main(self.event(), [{"sha": "a" * 40, "commit": {"message": "fix: x"}}]), 0)

    def test_attributed_commit_fails(self):
        commits = [{"sha": "b" * 40, "commit": {"message": HITS[0]}}]
        self.assertEqual(self.run_main(self.event(), commits), 1)

    def test_attributed_body_fails(self):
        self.assertEqual(self.run_main(self.event(body=HITS[4]), []), 1)

    def test_dependabot_is_exempt(self):
        event = self.event(body=HITS[4], user={"login": "dependabot[bot]"})
        self.assertEqual(self.run_main(event, [{"sha": "c" * 40, "commit": {"message": HITS[0]}}]), 0)

    def test_non_pr_event_is_a_no_op(self):
        with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as fh:
            json.dump({"ref": "refs/heads/main"}, fh)
        try:
            with mock.patch.dict(os.environ, {"GITHUB_EVENT_PATH": fh.name}):
                self.assertEqual(caa.main([]), 0)
        finally:
            os.unlink(fh.name)


if __name__ == "__main__":
    unittest.main()
