/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentCampaignsRouteImport } from './routes/agent-campaigns'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AttackersRouteImport } from './routes/attackers'
import { Route as AuthEventsRouteImport } from './routes/auth-events'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CanarytokensRouteImport } from './routes/canarytokens'
import { Route as CapeRouteImport } from './routes/cape'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DeadLettersRouteImport } from './routes/dead-letters'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GithubAnalysisRouteImport } from './routes/github-analysis'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IpsRouteImport } from './routes/ips'
import { Route as KillChainRouteImport } from './routes/kill-chain'
import { Route as LlmAnalysisRouteImport } from './routes/llm-analysis'
import { Route as MlAnomaliesRouteImport } from './routes/ml-anomalies'
import { Route as PayloadsRouteImport } from './routes/payloads'
import { Route as ProblemReportsRouteImport } from './routes/problem-reports'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RevdeckRouteImport } from './routes/revdeck'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourceHealthRouteImport } from './routes/source-health'
import { Route as TopologyRouteImport } from './routes/topology'
import { Route as ApiLiveRouteImport } from './routes/api/live'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as BffMountedSplatRouteImport } from './routes/bff-mounted.$'
import { Route as BffSplatRouteImport } from './routes/bff.$'
import { Route as CapeShaRouteImport } from './routes/cape.$sha'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ExportPortbridgeManualBlackholeDottxtRouteImport } from './routes/export.portbridge-manual-blackhole[.]txt'
import { Route as GhidraShaRouteImport } from './routes/ghidra.$sha'
import { Route as GithubAnalysisShaRouteImport } from './routes/github-analysis.$sha'
import { Route as InvestigateClusterRouteImport } from './routes/investigate.cluster'
import { Route as InvestigateLookupRouteImport } from './routes/investigate.lookup'
import { Route as PayloadAnalysisHashRouteImport } from './routes/payload-analysis.$hash'
import { Route as PayloadWorkbenchResultsRouteImport } from './routes/payload-workbench.results'
import { Route as RevdeckShaRouteImport } from './routes/revdeck.$sha'
import { Route as SandboxJobRouteImport } from './routes/sandbox.$job'
import { Route as SandboxVncRouteImport } from './routes/sandbox.vnc'
import { Route as SensorsIndexRouteImport } from './routes/sensors.index'
import { Route as SensorsSensorRouteImport } from './routes/sensors.$sensor'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as TtyReplayShasumRouteImport } from './routes/tty-replay.$shasum'
import { Route as ApiChartNameRouteImport } from './routes/api/chart.$name'
import { Route as ApiExportNameRouteImport } from './routes/api/export.$name'
import { Route as ApiTopologyFlowRouteImport } from './routes/api/topology.flow'
import { Route as InvestigateCidrCidrRouteImport } from './routes/investigate.cidr.$cidr'
import { Route as InvestigateIpIpRouteImport } from './routes/investigate.ip.$ip'
import { Route as ApiCanarytokenIdDownloadRouteImport } from './routes/api/canarytoken.$id.download'
import { Route as ApiPayloadHashDownloadRouteImport } from './routes/api/payload.$hash.download'
import { Route as ApiRawReportKindShaRouteImport } from './routes/api/raw-report.$kind.$sha'
import { Route as ApiRecordingShasumFormatRouteImport } from './routes/api/recording.$shasum.$format'
import { Route as ApiReportIdPdfRouteImport } from './routes/api/report.$id.pdf'
import { Route as ApiArtifactKindKeyFilenameRouteImport } from './routes/api/artifact.$kind.$key.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCampaignsRoute = AgentCampaignsRouteImport.update({
  id: '/agent-campaigns',
  path: '/agent-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackersRoute = AttackersRouteImport.update({
  id: '/attackers',
  path: '/attackers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEventsRoute = AuthEventsRouteImport.update({
  id: '/auth-events',
  path: '/auth-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CanarytokensRoute = CanarytokensRouteImport.update({
  id: '/canarytokens',
  path: '/canarytokens',
  getParentRoute: () => rootRouteImport,
} as any)
const CapeRoute = CapeRouteImport.update({
  id: '/cape',
  path: '/cape',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadLettersRoute = DeadLettersRouteImport.update({
  id: '/dead-letters',
  path: '/dead-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubAnalysisRoute = GithubAnalysisRouteImport.update({
  id: '/github-analysis',
  path: '/github-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IpsRoute = IpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => rootRouteImport,
} as any)
const KillChainRoute = KillChainRouteImport.update({
  id: '/kill-chain',
  path: '/kill-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmAnalysisRoute = LlmAnalysisRouteImport.update({
  id: '/llm-analysis',
  path: '/llm-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MlAnomaliesRoute = MlAnomaliesRouteImport.update({
  id: '/ml-anomalies',
  path: '/ml-anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadsRoute = PayloadsRouteImport.update({
  id: '/payloads',
  path: '/payloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemReportsRoute = ProblemReportsRouteImport.update({
  id: '/problem-reports',
  path: '/problem-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RevdeckRoute = RevdeckRouteImport.update({
  id: '/revdeck',
  path: '/revdeck',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceHealthRoute = SourceHealthRouteImport.update({
  id: '/source-health',
  path: '/source-health',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const BffMountedSplatRoute = BffMountedSplatRouteImport.update({
  id: '/bff-mounted/$',
  path: '/bff-mounted/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BffSplatRoute = BffSplatRouteImport.update({
  id: '/bff/$',
  path: '/bff/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CapeShaRoute = CapeShaRouteImport.update({
  id: '/$sha',
  path: '/$sha',
  getParentRoute: () => CapeRoute,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportPortbridgeManualBlackholeDottxtRoute =
  ExportPortbridgeManualBlackholeDottxtRouteImport.update({
    id: '/export/portbridge-manual-blackhole.txt',
    path: '/export/portbridge-manual-blackhole.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const GhidraShaRoute = GhidraShaRouteImport.update({
  id: '/ghidra/$sha',
  path: '/ghidra/$sha',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubAnalysisShaRoute = GithubAnalysisShaRouteImport.update({
  id: '/$sha',
  path: '/$sha',
  getParentRoute: () => GithubAnalysisRoute,
} as any)
const InvestigateClusterRoute = InvestigateClusterRouteImport.update({
  id: '/investigate/cluster',
  path: '/investigate/cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateLookupRoute = InvestigateLookupRouteImport.update({
  id: '/investigate/lookup',
  path: '/investigate/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadAnalysisHashRoute = PayloadAnalysisHashRouteImport.update({
  id: '/payload-analysis/$hash',
  path: '/payload-analysis/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadWorkbenchResultsRoute = PayloadWorkbenchResultsRouteImport.update({
  id: '/payload-workbench/results',
  path: '/payload-workbench/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RevdeckShaRoute = RevdeckShaRouteImport.update({
  id: '/$sha',
  path: '/$sha',
  getParentRoute: () => RevdeckRoute,
} as any)
const SandboxJobRoute = SandboxJobRouteImport.update({
  id: '/sandbox/$job',
  path: '/sandbox/$job',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxVncRoute = SandboxVncRouteImport.update({
  id: '/sandbox/vnc',
  path: '/sandbox/vnc',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsIndexRoute = SensorsIndexRouteImport.update({
  id: '/sensors/',
  path: '/sensors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsSensorRoute = SensorsSensorRouteImport.update({
  id: '/sensors/$sensor',
  path: '/sensors/$sensor',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TtyReplayShasumRoute = TtyReplayShasumRouteImport.update({
  id: '/tty-replay/$shasum',
  path: '/tty-replay/$shasum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartNameRoute = ApiChartNameRouteImport.update({
  id: '/api/chart/$name',
  path: '/api/chart/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportNameRoute = ApiExportNameRouteImport.update({
  id: '/api/export/$name',
  path: '/api/export/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopologyFlowRoute = ApiTopologyFlowRouteImport.update({
  id: '/api/topology/flow',
  path: '/api/topology/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateCidrCidrRoute = InvestigateCidrCidrRouteImport.update({
  id: '/investigate/cidr/$cidr',
  path: '/investigate/cidr/$cidr',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateIpIpRoute = InvestigateIpIpRouteImport.update({
  id: '/investigate/ip/$ip',
  path: '/investigate/ip/$ip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCanarytokenIdDownloadRoute =
  ApiCanarytokenIdDownloadRouteImport.update({
    id: '/api/canarytoken/$id/download',
    path: '/api/canarytoken/$id/download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPayloadHashDownloadRoute = ApiPayloadHashDownloadRouteImport.update({
  id: '/api/payload/$hash/download',
  path: '/api/payload/$hash/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawReportKindShaRoute = ApiRawReportKindShaRouteImport.update({
  id: '/api/raw-report/$kind/$sha',
  path: '/api/raw-report/$kind/$sha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordingShasumFormatRoute =
  ApiRecordingShasumFormatRouteImport.update({
    id: '/api/recording/$shasum/$format',
    path: '/api/recording/$shasum/$format',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReportIdPdfRoute = ApiReportIdPdfRouteImport.update({
  id: '/api/report/$id/pdf',
  path: '/api/report/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactKindKeyFilenameRoute =
  ApiArtifactKindKeyFilenameRouteImport.update({
    id: '/api/artifact/$kind/$key/$filename',
    path: '/api/artifact/$kind/$key/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-campaigns': typeof AgentCampaignsRoute
  '/alerts': typeof AlertsRoute
  '/attackers': typeof AttackersRoute
  '/auth-events': typeof AuthEventsRoute
  '/campaigns': typeof CampaignsRoute
  '/canarytokens': typeof CanarytokensRoute
  '/cape': typeof CapeRouteWithChildren
  '/clusters': typeof ClustersRoute
  '/commands': typeof CommandsRoute
  '/credentials': typeof CredentialsRoute
  '/dead-letters': typeof DeadLettersRoute
  '/events': typeof EventsRoute
  '/github-analysis': typeof GithubAnalysisRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/history': typeof HistoryRoute
  '/ips': typeof IpsRoute
  '/kill-chain': typeof KillChainRoute
  '/llm-analysis': typeof LlmAnalysisRoute
  '/ml-anomalies': typeof MlAnomaliesRoute
  '/payloads': typeof PayloadsRoute
  '/problem-reports': typeof ProblemReportsRoute
  '/recordings': typeof RecordingsRoute
  '/reports': typeof ReportsRoute
  '/revdeck': typeof RevdeckRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/source-health': typeof SourceHealthRoute
  '/topology': typeof TopologyRoute
  '/api/live': typeof ApiLiveRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/bff-mounted/$': typeof BffMountedSplatRoute
  '/bff/$': typeof BffSplatRoute
  '/cape/$sha': typeof CapeShaRoute
  '/event/$id': typeof EventIdRoute
  '/export/portbridge-manual-blackhole.txt': typeof ExportPortbridgeManualBlackholeDottxtRoute
  '/ghidra/$sha': typeof GhidraShaRoute
  '/github-analysis/$sha': typeof GithubAnalysisShaRoute
  '/investigate/cluster': typeof InvestigateClusterRoute
  '/investigate/lookup': typeof InvestigateLookupRoute
  '/payload-analysis/$hash': typeof PayloadAnalysisHashRoute
  '/payload-workbench/results': typeof PayloadWorkbenchResultsRoute
  '/revdeck/$sha': typeof RevdeckShaRoute
  '/sandbox/$job': typeof SandboxJobRoute
  '/sandbox/vnc': typeof SandboxVncRoute
  '/sensors/$sensor': typeof SensorsSensorRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/tty-replay/$shasum': typeof TtyReplayShasumRoute
  '/sensors/': typeof SensorsIndexRoute
  '/api/chart/$name': typeof ApiChartNameRoute
  '/api/export/$name': typeof ApiExportNameRoute
  '/api/topology/flow': typeof ApiTopologyFlowRoute
  '/investigate/cidr/$cidr': typeof InvestigateCidrCidrRoute
  '/investigate/ip/$ip': typeof InvestigateIpIpRoute
  '/api/canarytoken/$id/download': typeof ApiCanarytokenIdDownloadRoute
  '/api/payload/$hash/download': typeof ApiPayloadHashDownloadRoute
  '/api/raw-report/$kind/$sha': typeof ApiRawReportKindShaRoute
  '/api/recording/$shasum/$format': typeof ApiRecordingShasumFormatRoute
  '/api/report/$id/pdf': typeof ApiReportIdPdfRoute
  '/api/artifact/$kind/$key/$filename': typeof ApiArtifactKindKeyFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-campaigns': typeof AgentCampaignsRoute
  '/alerts': typeof AlertsRoute
  '/attackers': typeof AttackersRoute
  '/auth-events': typeof AuthEventsRoute
  '/campaigns': typeof CampaignsRoute
  '/canarytokens': typeof CanarytokensRoute
  '/cape': typeof CapeRouteWithChildren
  '/clusters': typeof ClustersRoute
  '/commands': typeof CommandsRoute
  '/credentials': typeof CredentialsRoute
  '/dead-letters': typeof DeadLettersRoute
  '/events': typeof EventsRoute
  '/github-analysis': typeof GithubAnalysisRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/history': typeof HistoryRoute
  '/ips': typeof IpsRoute
  '/kill-chain': typeof KillChainRoute
  '/llm-analysis': typeof LlmAnalysisRoute
  '/ml-anomalies': typeof MlAnomaliesRoute
  '/payloads': typeof PayloadsRoute
  '/problem-reports': typeof ProblemReportsRoute
  '/recordings': typeof RecordingsRoute
  '/reports': typeof ReportsRoute
  '/revdeck': typeof RevdeckRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/source-health': typeof SourceHealthRoute
  '/topology': typeof TopologyRoute
  '/api/live': typeof ApiLiveRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/bff-mounted/$': typeof BffMountedSplatRoute
  '/bff/$': typeof BffSplatRoute
  '/cape/$sha': typeof CapeShaRoute
  '/event/$id': typeof EventIdRoute
  '/export/portbridge-manual-blackhole.txt': typeof ExportPortbridgeManualBlackholeDottxtRoute
  '/ghidra/$sha': typeof GhidraShaRoute
  '/github-analysis/$sha': typeof GithubAnalysisShaRoute
  '/investigate/cluster': typeof InvestigateClusterRoute
  '/investigate/lookup': typeof InvestigateLookupRoute
  '/payload-analysis/$hash': typeof PayloadAnalysisHashRoute
  '/payload-workbench/results': typeof PayloadWorkbenchResultsRoute
  '/revdeck/$sha': typeof RevdeckShaRoute
  '/sandbox/$job': typeof SandboxJobRoute
  '/sandbox/vnc': typeof SandboxVncRoute
  '/sensors/$sensor': typeof SensorsSensorRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/tty-replay/$shasum': typeof TtyReplayShasumRoute
  '/sensors': typeof SensorsIndexRoute
  '/api/chart/$name': typeof ApiChartNameRoute
  '/api/export/$name': typeof ApiExportNameRoute
  '/api/topology/flow': typeof ApiTopologyFlowRoute
  '/investigate/cidr/$cidr': typeof InvestigateCidrCidrRoute
  '/investigate/ip/$ip': typeof InvestigateIpIpRoute
  '/api/canarytoken/$id/download': typeof ApiCanarytokenIdDownloadRoute
  '/api/payload/$hash/download': typeof ApiPayloadHashDownloadRoute
  '/api/raw-report/$kind/$sha': typeof ApiRawReportKindShaRoute
  '/api/recording/$shasum/$format': typeof ApiRecordingShasumFormatRoute
  '/api/report/$id/pdf': typeof ApiReportIdPdfRoute
  '/api/artifact/$kind/$key/$filename': typeof ApiArtifactKindKeyFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-campaigns': typeof AgentCampaignsRoute
  '/alerts': typeof AlertsRoute
  '/attackers': typeof AttackersRoute
  '/auth-events': typeof AuthEventsRoute
  '/campaigns': typeof CampaignsRoute
  '/canarytokens': typeof CanarytokensRoute
  '/cape': typeof CapeRouteWithChildren
  '/clusters': typeof ClustersRoute
  '/commands': typeof CommandsRoute
  '/credentials': typeof CredentialsRoute
  '/dead-letters': typeof DeadLettersRoute
  '/events': typeof EventsRoute
  '/github-analysis': typeof GithubAnalysisRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/history': typeof HistoryRoute
  '/ips': typeof IpsRoute
  '/kill-chain': typeof KillChainRoute
  '/llm-analysis': typeof LlmAnalysisRoute
  '/ml-anomalies': typeof MlAnomaliesRoute
  '/payloads': typeof PayloadsRoute
  '/problem-reports': typeof ProblemReportsRoute
  '/recordings': typeof RecordingsRoute
  '/reports': typeof ReportsRoute
  '/revdeck': typeof RevdeckRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/source-health': typeof SourceHealthRoute
  '/topology': typeof TopologyRoute
  '/api/live': typeof ApiLiveRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/bff-mounted/$': typeof BffMountedSplatRoute
  '/bff/$': typeof BffSplatRoute
  '/cape/$sha': typeof CapeShaRoute
  '/event/$id': typeof EventIdRoute
  '/export/portbridge-manual-blackhole.txt': typeof ExportPortbridgeManualBlackholeDottxtRoute
  '/ghidra/$sha': typeof GhidraShaRoute
  '/github-analysis/$sha': typeof GithubAnalysisShaRoute
  '/investigate/cluster': typeof InvestigateClusterRoute
  '/investigate/lookup': typeof InvestigateLookupRoute
  '/payload-analysis/$hash': typeof PayloadAnalysisHashRoute
  '/payload-workbench/results': typeof PayloadWorkbenchResultsRoute
  '/revdeck/$sha': typeof RevdeckShaRoute
  '/sandbox/$job': typeof SandboxJobRoute
  '/sandbox/vnc': typeof SandboxVncRoute
  '/sensors/$sensor': typeof SensorsSensorRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/tty-replay/$shasum': typeof TtyReplayShasumRoute
  '/sensors/': typeof SensorsIndexRoute
  '/api/chart/$name': typeof ApiChartNameRoute
  '/api/export/$name': typeof ApiExportNameRoute
  '/api/topology/flow': typeof ApiTopologyFlowRoute
  '/investigate/cidr/$cidr': typeof InvestigateCidrCidrRoute
  '/investigate/ip/$ip': typeof InvestigateIpIpRoute
  '/api/canarytoken/$id/download': typeof ApiCanarytokenIdDownloadRoute
  '/api/payload/$hash/download': typeof ApiPayloadHashDownloadRoute
  '/api/raw-report/$kind/$sha': typeof ApiRawReportKindShaRoute
  '/api/recording/$shasum/$format': typeof ApiRecordingShasumFormatRoute
  '/api/report/$id/pdf': typeof ApiReportIdPdfRoute
  '/api/artifact/$kind/$key/$filename': typeof ApiArtifactKindKeyFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-campaigns'
    | '/alerts'
    | '/attackers'
    | '/auth-events'
    | '/campaigns'
    | '/canarytokens'
    | '/cape'
    | '/clusters'
    | '/commands'
    | '/credentials'
    | '/dead-letters'
    | '/events'
    | '/github-analysis'
    | '/healthz'
    | '/history'
    | '/ips'
    | '/kill-chain'
    | '/llm-analysis'
    | '/ml-anomalies'
    | '/payloads'
    | '/problem-reports'
    | '/recordings'
    | '/reports'
    | '/revdeck'
    | '/search'
    | '/settings'
    | '/source-health'
    | '/topology'
    | '/api/live'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/bff-mounted/$'
    | '/bff/$'
    | '/cape/$sha'
    | '/event/$id'
    | '/export/portbridge-manual-blackhole.txt'
    | '/ghidra/$sha'
    | '/github-analysis/$sha'
    | '/investigate/cluster'
    | '/investigate/lookup'
    | '/payload-analysis/$hash'
    | '/payload-workbench/results'
    | '/revdeck/$sha'
    | '/sandbox/$job'
    | '/sandbox/vnc'
    | '/sensors/$sensor'
    | '/sessions/$id'
    | '/tty-replay/$shasum'
    | '/sensors/'
    | '/api/chart/$name'
    | '/api/export/$name'
    | '/api/topology/flow'
    | '/investigate/cidr/$cidr'
    | '/investigate/ip/$ip'
    | '/api/canarytoken/$id/download'
    | '/api/payload/$hash/download'
    | '/api/raw-report/$kind/$sha'
    | '/api/recording/$shasum/$format'
    | '/api/report/$id/pdf'
    | '/api/artifact/$kind/$key/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-campaigns'
    | '/alerts'
    | '/attackers'
    | '/auth-events'
    | '/campaigns'
    | '/canarytokens'
    | '/cape'
    | '/clusters'
    | '/commands'
    | '/credentials'
    | '/dead-letters'
    | '/events'
    | '/github-analysis'
    | '/healthz'
    | '/history'
    | '/ips'
    | '/kill-chain'
    | '/llm-analysis'
    | '/ml-anomalies'
    | '/payloads'
    | '/problem-reports'
    | '/recordings'
    | '/reports'
    | '/revdeck'
    | '/search'
    | '/settings'
    | '/source-health'
    | '/topology'
    | '/api/live'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/bff-mounted/$'
    | '/bff/$'
    | '/cape/$sha'
    | '/event/$id'
    | '/export/portbridge-manual-blackhole.txt'
    | '/ghidra/$sha'
    | '/github-analysis/$sha'
    | '/investigate/cluster'
    | '/investigate/lookup'
    | '/payload-analysis/$hash'
    | '/payload-workbench/results'
    | '/revdeck/$sha'
    | '/sandbox/$job'
    | '/sandbox/vnc'
    | '/sensors/$sensor'
    | '/sessions/$id'
    | '/tty-replay/$shasum'
    | '/sensors'
    | '/api/chart/$name'
    | '/api/export/$name'
    | '/api/topology/flow'
    | '/investigate/cidr/$cidr'
    | '/investigate/ip/$ip'
    | '/api/canarytoken/$id/download'
    | '/api/payload/$hash/download'
    | '/api/raw-report/$kind/$sha'
    | '/api/recording/$shasum/$format'
    | '/api/report/$id/pdf'
    | '/api/artifact/$kind/$key/$filename'
  id:
    | '__root__'
    | '/'
    | '/agent-campaigns'
    | '/alerts'
    | '/attackers'
    | '/auth-events'
    | '/campaigns'
    | '/canarytokens'
    | '/cape'
    | '/clusters'
    | '/commands'
    | '/credentials'
    | '/dead-letters'
    | '/events'
    | '/github-analysis'
    | '/healthz'
    | '/history'
    | '/ips'
    | '/kill-chain'
    | '/llm-analysis'
    | '/ml-anomalies'
    | '/payloads'
    | '/problem-reports'
    | '/recordings'
    | '/reports'
    | '/revdeck'
    | '/search'
    | '/settings'
    | '/source-health'
    | '/topology'
    | '/api/live'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/bff-mounted/$'
    | '/bff/$'
    | '/cape/$sha'
    | '/event/$id'
    | '/export/portbridge-manual-blackhole.txt'
    | '/ghidra/$sha'
    | '/github-analysis/$sha'
    | '/investigate/cluster'
    | '/investigate/lookup'
    | '/payload-analysis/$hash'
    | '/payload-workbench/results'
    | '/revdeck/$sha'
    | '/sandbox/$job'
    | '/sandbox/vnc'
    | '/sensors/$sensor'
    | '/sessions/$id'
    | '/tty-replay/$shasum'
    | '/sensors/'
    | '/api/chart/$name'
    | '/api/export/$name'
    | '/api/topology/flow'
    | '/investigate/cidr/$cidr'
    | '/investigate/ip/$ip'
    | '/api/canarytoken/$id/download'
    | '/api/payload/$hash/download'
    | '/api/raw-report/$kind/$sha'
    | '/api/recording/$shasum/$format'
    | '/api/report/$id/pdf'
    | '/api/artifact/$kind/$key/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentCampaignsRoute: typeof AgentCampaignsRoute
  AlertsRoute: typeof AlertsRoute
  AttackersRoute: typeof AttackersRoute
  AuthEventsRoute: typeof AuthEventsRoute
  CampaignsRoute: typeof CampaignsRoute
  CanarytokensRoute: typeof CanarytokensRoute
  CapeRoute: typeof CapeRouteWithChildren
  ClustersRoute: typeof ClustersRoute
  CommandsRoute: typeof CommandsRoute
  CredentialsRoute: typeof CredentialsRoute
  DeadLettersRoute: typeof DeadLettersRoute
  EventsRoute: typeof EventsRoute
  GithubAnalysisRoute: typeof GithubAnalysisRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  HistoryRoute: typeof HistoryRoute
  IpsRoute: typeof IpsRoute
  KillChainRoute: typeof KillChainRoute
  LlmAnalysisRoute: typeof LlmAnalysisRoute
  MlAnomaliesRoute: typeof MlAnomaliesRoute
  PayloadsRoute: typeof PayloadsRoute
  ProblemReportsRoute: typeof ProblemReportsRoute
  RecordingsRoute: typeof RecordingsRoute
  ReportsRoute: typeof ReportsRoute
  RevdeckRoute: typeof RevdeckRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SourceHealthRoute: typeof SourceHealthRoute
  TopologyRoute: typeof TopologyRoute
  ApiLiveRoute: typeof ApiLiveRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  BffMountedSplatRoute: typeof BffMountedSplatRoute
  BffSplatRoute: typeof BffSplatRoute
  EventIdRoute: typeof EventIdRoute
  ExportPortbridgeManualBlackholeDottxtRoute: typeof ExportPortbridgeManualBlackholeDottxtRoute
  GhidraShaRoute: typeof GhidraShaRoute
  InvestigateClusterRoute: typeof InvestigateClusterRoute
  InvestigateLookupRoute: typeof InvestigateLookupRoute
  PayloadAnalysisHashRoute: typeof PayloadAnalysisHashRoute
  PayloadWorkbenchResultsRoute: typeof PayloadWorkbenchResultsRoute
  SandboxJobRoute: typeof SandboxJobRoute
  SandboxVncRoute: typeof SandboxVncRoute
  SensorsSensorRoute: typeof SensorsSensorRoute
  SessionsIdRoute: typeof SessionsIdRoute
  TtyReplayShasumRoute: typeof TtyReplayShasumRoute
  SensorsIndexRoute: typeof SensorsIndexRoute
  ApiChartNameRoute: typeof ApiChartNameRoute
  ApiExportNameRoute: typeof ApiExportNameRoute
  ApiTopologyFlowRoute: typeof ApiTopologyFlowRoute
  InvestigateCidrCidrRoute: typeof InvestigateCidrCidrRoute
  InvestigateIpIpRoute: typeof InvestigateIpIpRoute
  ApiCanarytokenIdDownloadRoute: typeof ApiCanarytokenIdDownloadRoute
  ApiPayloadHashDownloadRoute: typeof ApiPayloadHashDownloadRoute
  ApiRawReportKindShaRoute: typeof ApiRawReportKindShaRoute
  ApiRecordingShasumFormatRoute: typeof ApiRecordingShasumFormatRoute
  ApiReportIdPdfRoute: typeof ApiReportIdPdfRoute
  ApiArtifactKindKeyFilenameRoute: typeof ApiArtifactKindKeyFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-campaigns': {
      id: '/agent-campaigns'
      path: '/agent-campaigns'
      fullPath: '/agent-campaigns'
      preLoaderRoute: typeof AgentCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attackers': {
      id: '/attackers'
      path: '/attackers'
      fullPath: '/attackers'
      preLoaderRoute: typeof AttackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-events': {
      id: '/auth-events'
      path: '/auth-events'
      fullPath: '/auth-events'
      preLoaderRoute: typeof AuthEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canarytokens': {
      id: '/canarytokens'
      path: '/canarytokens'
      fullPath: '/canarytokens'
      preLoaderRoute: typeof CanarytokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cape': {
      id: '/cape'
      path: '/cape'
      fullPath: '/cape'
      preLoaderRoute: typeof CapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-letters': {
      id: '/dead-letters'
      path: '/dead-letters'
      fullPath: '/dead-letters'
      preLoaderRoute: typeof DeadLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-analysis': {
      id: '/github-analysis'
      path: '/github-analysis'
      fullPath: '/github-analysis'
      preLoaderRoute: typeof GithubAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ips': {
      id: '/ips'
      path: '/ips'
      fullPath: '/ips'
      preLoaderRoute: typeof IpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kill-chain': {
      id: '/kill-chain'
      path: '/kill-chain'
      fullPath: '/kill-chain'
      preLoaderRoute: typeof KillChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-analysis': {
      id: '/llm-analysis'
      path: '/llm-analysis'
      fullPath: '/llm-analysis'
      preLoaderRoute: typeof LlmAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-anomalies': {
      id: '/ml-anomalies'
      path: '/ml-anomalies'
      fullPath: '/ml-anomalies'
      preLoaderRoute: typeof MlAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payloads': {
      id: '/payloads'
      path: '/payloads'
      fullPath: '/payloads'
      preLoaderRoute: typeof PayloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-reports': {
      id: '/problem-reports'
      path: '/problem-reports'
      fullPath: '/problem-reports'
      preLoaderRoute: typeof ProblemReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revdeck': {
      id: '/revdeck'
      path: '/revdeck'
      fullPath: '/revdeck'
      preLoaderRoute: typeof RevdeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-health': {
      id: '/source-health'
      path: '/source-health'
      fullPath: '/source-health'
      preLoaderRoute: typeof SourceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff-mounted/$': {
      id: '/bff-mounted/$'
      path: '/bff-mounted/$'
      fullPath: '/bff-mounted/$'
      preLoaderRoute: typeof BffMountedSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bff/$': {
      id: '/bff/$'
      path: '/bff/$'
      fullPath: '/bff/$'
      preLoaderRoute: typeof BffSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cape/$sha': {
      id: '/cape/$sha'
      path: '/$sha'
      fullPath: '/cape/$sha'
      preLoaderRoute: typeof CapeShaRouteImport
      parentRoute: typeof CapeRoute
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/portbridge-manual-blackhole.txt': {
      id: '/export/portbridge-manual-blackhole.txt'
      path: '/export/portbridge-manual-blackhole.txt'
      fullPath: '/export/portbridge-manual-blackhole.txt'
      preLoaderRoute: typeof ExportPortbridgeManualBlackholeDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghidra/$sha': {
      id: '/ghidra/$sha'
      path: '/ghidra/$sha'
      fullPath: '/ghidra/$sha'
      preLoaderRoute: typeof GhidraShaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-analysis/$sha': {
      id: '/github-analysis/$sha'
      path: '/$sha'
      fullPath: '/github-analysis/$sha'
      preLoaderRoute: typeof GithubAnalysisShaRouteImport
      parentRoute: typeof GithubAnalysisRoute
    }
    '/investigate/cluster': {
      id: '/investigate/cluster'
      path: '/investigate/cluster'
      fullPath: '/investigate/cluster'
      preLoaderRoute: typeof InvestigateClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/lookup': {
      id: '/investigate/lookup'
      path: '/investigate/lookup'
      fullPath: '/investigate/lookup'
      preLoaderRoute: typeof InvestigateLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payload-analysis/$hash': {
      id: '/payload-analysis/$hash'
      path: '/payload-analysis/$hash'
      fullPath: '/payload-analysis/$hash'
      preLoaderRoute: typeof PayloadAnalysisHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payload-workbench/results': {
      id: '/payload-workbench/results'
      path: '/payload-workbench/results'
      fullPath: '/payload-workbench/results'
      preLoaderRoute: typeof PayloadWorkbenchResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revdeck/$sha': {
      id: '/revdeck/$sha'
      path: '/$sha'
      fullPath: '/revdeck/$sha'
      preLoaderRoute: typeof RevdeckShaRouteImport
      parentRoute: typeof RevdeckRoute
    }
    '/sandbox/$job': {
      id: '/sandbox/$job'
      path: '/sandbox/$job'
      fullPath: '/sandbox/$job'
      preLoaderRoute: typeof SandboxJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/vnc': {
      id: '/sandbox/vnc'
      path: '/sandbox/vnc'
      fullPath: '/sandbox/vnc'
      preLoaderRoute: typeof SandboxVncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/': {
      id: '/sensors/'
      path: '/sensors'
      fullPath: '/sensors/'
      preLoaderRoute: typeof SensorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/$sensor': {
      id: '/sensors/$sensor'
      path: '/sensors/$sensor'
      fullPath: '/sensors/$sensor'
      preLoaderRoute: typeof SensorsSensorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tty-replay/$shasum': {
      id: '/tty-replay/$shasum'
      path: '/tty-replay/$shasum'
      fullPath: '/tty-replay/$shasum'
      preLoaderRoute: typeof TtyReplayShasumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chart/$name': {
      id: '/api/chart/$name'
      path: '/api/chart/$name'
      fullPath: '/api/chart/$name'
      preLoaderRoute: typeof ApiChartNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$name': {
      id: '/api/export/$name'
      path: '/api/export/$name'
      fullPath: '/api/export/$name'
      preLoaderRoute: typeof ApiExportNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/topology/flow': {
      id: '/api/topology/flow'
      path: '/api/topology/flow'
      fullPath: '/api/topology/flow'
      preLoaderRoute: typeof ApiTopologyFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/cidr/$cidr': {
      id: '/investigate/cidr/$cidr'
      path: '/investigate/cidr/$cidr'
      fullPath: '/investigate/cidr/$cidr'
      preLoaderRoute: typeof InvestigateCidrCidrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/ip/$ip': {
      id: '/investigate/ip/$ip'
      path: '/investigate/ip/$ip'
      fullPath: '/investigate/ip/$ip'
      preLoaderRoute: typeof InvestigateIpIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/canarytoken/$id/download': {
      id: '/api/canarytoken/$id/download'
      path: '/api/canarytoken/$id/download'
      fullPath: '/api/canarytoken/$id/download'
      preLoaderRoute: typeof ApiCanarytokenIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payload/$hash/download': {
      id: '/api/payload/$hash/download'
      path: '/api/payload/$hash/download'
      fullPath: '/api/payload/$hash/download'
      preLoaderRoute: typeof ApiPayloadHashDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw-report/$kind/$sha': {
      id: '/api/raw-report/$kind/$sha'
      path: '/api/raw-report/$kind/$sha'
      fullPath: '/api/raw-report/$kind/$sha'
      preLoaderRoute: typeof ApiRawReportKindShaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recording/$shasum/$format': {
      id: '/api/recording/$shasum/$format'
      path: '/api/recording/$shasum/$format'
      fullPath: '/api/recording/$shasum/$format'
      preLoaderRoute: typeof ApiRecordingShasumFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report/$id/pdf': {
      id: '/api/report/$id/pdf'
      path: '/api/report/$id/pdf'
      fullPath: '/api/report/$id/pdf'
      preLoaderRoute: typeof ApiReportIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact/$kind/$key/$filename': {
      id: '/api/artifact/$kind/$key/$filename'
      path: '/api/artifact/$kind/$key/$filename'
      fullPath: '/api/artifact/$kind/$key/$filename'
      preLoaderRoute: typeof ApiArtifactKindKeyFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CapeRouteChildren {
  CapeShaRoute: typeof CapeShaRoute
}

const CapeRouteChildren: CapeRouteChildren = {
  CapeShaRoute: CapeShaRoute,
}

const CapeRouteWithChildren = CapeRoute._addFileChildren(CapeRouteChildren)

interface GithubAnalysisRouteChildren {
  GithubAnalysisShaRoute: typeof GithubAnalysisShaRoute
}

const GithubAnalysisRouteChildren: GithubAnalysisRouteChildren = {
  GithubAnalysisShaRoute: GithubAnalysisShaRoute,
}

const GithubAnalysisRouteWithChildren = GithubAnalysisRoute._addFileChildren(
  GithubAnalysisRouteChildren,
)

interface RevdeckRouteChildren {
  RevdeckShaRoute: typeof RevdeckShaRoute
}

const RevdeckRouteChildren: RevdeckRouteChildren = {
  RevdeckShaRoute: RevdeckShaRoute,
}

const RevdeckRouteWithChildren =
  RevdeckRoute._addFileChildren(RevdeckRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentCampaignsRoute: AgentCampaignsRoute,
  AlertsRoute: AlertsRoute,
  AttackersRoute: AttackersRoute,
  AuthEventsRoute: AuthEventsRoute,
  CampaignsRoute: CampaignsRoute,
  CanarytokensRoute: CanarytokensRoute,
  CapeRoute: CapeRouteWithChildren,
  ClustersRoute: ClustersRoute,
  CommandsRoute: CommandsRoute,
  CredentialsRoute: CredentialsRoute,
  DeadLettersRoute: DeadLettersRoute,
  EventsRoute: EventsRoute,
  GithubAnalysisRoute: GithubAnalysisRouteWithChildren,
  HealthzRoute: HealthzRoute,
  HistoryRoute: HistoryRoute,
  IpsRoute: IpsRoute,
  KillChainRoute: KillChainRoute,
  LlmAnalysisRoute: LlmAnalysisRoute,
  MlAnomaliesRoute: MlAnomaliesRoute,
  PayloadsRoute: PayloadsRoute,
  ProblemReportsRoute: ProblemReportsRoute,
  RecordingsRoute: RecordingsRoute,
  ReportsRoute: ReportsRoute,
  RevdeckRoute: RevdeckRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SourceHealthRoute: SourceHealthRoute,
  TopologyRoute: TopologyRoute,
  ApiLiveRoute: ApiLiveRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  BffMountedSplatRoute: BffMountedSplatRoute,
  BffSplatRoute: BffSplatRoute,
  EventIdRoute: EventIdRoute,
  ExportPortbridgeManualBlackholeDottxtRoute:
    ExportPortbridgeManualBlackholeDottxtRoute,
  GhidraShaRoute: GhidraShaRoute,
  InvestigateClusterRoute: InvestigateClusterRoute,
  InvestigateLookupRoute: InvestigateLookupRoute,
  PayloadAnalysisHashRoute: PayloadAnalysisHashRoute,
  PayloadWorkbenchResultsRoute: PayloadWorkbenchResultsRoute,
  SandboxJobRoute: SandboxJobRoute,
  SandboxVncRoute: SandboxVncRoute,
  SensorsSensorRoute: SensorsSensorRoute,
  SessionsIdRoute: SessionsIdRoute,
  TtyReplayShasumRoute: TtyReplayShasumRoute,
  SensorsIndexRoute: SensorsIndexRoute,
  ApiChartNameRoute: ApiChartNameRoute,
  ApiExportNameRoute: ApiExportNameRoute,
  ApiTopologyFlowRoute: ApiTopologyFlowRoute,
  InvestigateCidrCidrRoute: InvestigateCidrCidrRoute,
  InvestigateIpIpRoute: InvestigateIpIpRoute,
  ApiCanarytokenIdDownloadRoute: ApiCanarytokenIdDownloadRoute,
  ApiPayloadHashDownloadRoute: ApiPayloadHashDownloadRoute,
  ApiRawReportKindShaRoute: ApiRawReportKindShaRoute,
  ApiRecordingShasumFormatRoute: ApiRecordingShasumFormatRoute,
  ApiReportIdPdfRoute: ApiReportIdPdfRoute,
  ApiArtifactKindKeyFilenameRoute: ApiArtifactKindKeyFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
