/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentCampaignsRouteImport } from './routes/agent-campaigns'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AttackersRouteImport } from './routes/attackers'
import { Route as AuthEventsRouteImport } from './routes/auth-events'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IpsRouteImport } from './routes/ips'
import { Route as MlAnomaliesRouteImport } from './routes/ml-anomalies'
import { Route as PayloadsRouteImport } from './routes/payloads'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCampaignsRoute = AgentCampaignsRouteImport.update({
  id: '/agent-campaigns',
  path: '/agent-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackersRoute = AttackersRouteImport.update({
  id: '/attackers',
  path: '/attackers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEventsRoute = AuthEventsRouteImport.update({
  id: '/auth-events',
  path: '/auth-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IpsRoute = IpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => rootRouteImport,
} as any)
const MlAnomaliesRoute = MlAnomaliesRouteImport.update({
  id: '/ml-anomalies',
  path: '/ml-anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadsRoute = PayloadsRouteImport.update({
  id: '/payloads',
  path: '/payloads',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-campaigns': typeof AgentCampaignsRoute
  '/alerts': typeof AlertsRoute
  '/attackers': typeof AttackersRoute
  '/auth-events': typeof AuthEventsRoute
  '/campaigns': typeof CampaignsRoute
  '/clusters': typeof ClustersRoute
  '/commands': typeof CommandsRoute
  '/events': typeof EventsRoute
  '/ips': typeof IpsRoute
  '/ml-anomalies': typeof MlAnomaliesRoute
  '/payloads': typeof PayloadsRoute
  '/recordings': typeof RecordingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-campaigns': typeof AgentCampaignsRoute
  '/alerts': typeof AlertsRoute
  '/attackers': typeof AttackersRoute
  '/auth-events': typeof AuthEventsRoute
  '/campaigns': typeof CampaignsRoute
  '/clusters': typeof ClustersRoute
  '/commands': typeof CommandsRoute
  '/events': typeof EventsRoute
  '/ips': typeof IpsRoute
  '/ml-anomalies': typeof MlAnomaliesRoute
  '/payloads': typeof PayloadsRoute
  '/recordings': typeof RecordingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-campaigns': typeof AgentCampaignsRoute
  '/alerts': typeof AlertsRoute
  '/attackers': typeof AttackersRoute
  '/auth-events': typeof AuthEventsRoute
  '/campaigns': typeof CampaignsRoute
  '/clusters': typeof ClustersRoute
  '/commands': typeof CommandsRoute
  '/events': typeof EventsRoute
  '/ips': typeof IpsRoute
  '/ml-anomalies': typeof MlAnomaliesRoute
  '/payloads': typeof PayloadsRoute
  '/recordings': typeof RecordingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-campaigns'
    | '/alerts'
    | '/attackers'
    | '/auth-events'
    | '/campaigns'
    | '/clusters'
    | '/commands'
    | '/events'
    | '/ips'
    | '/ml-anomalies'
    | '/payloads'
    | '/recordings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-campaigns'
    | '/alerts'
    | '/attackers'
    | '/auth-events'
    | '/campaigns'
    | '/clusters'
    | '/commands'
    | '/events'
    | '/ips'
    | '/ml-anomalies'
    | '/payloads'
    | '/recordings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/agent-campaigns'
    | '/alerts'
    | '/attackers'
    | '/auth-events'
    | '/campaigns'
    | '/clusters'
    | '/commands'
    | '/events'
    | '/ips'
    | '/ml-anomalies'
    | '/payloads'
    | '/recordings'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentCampaignsRoute: typeof AgentCampaignsRoute
  AlertsRoute: typeof AlertsRoute
  AttackersRoute: typeof AttackersRoute
  AuthEventsRoute: typeof AuthEventsRoute
  CampaignsRoute: typeof CampaignsRoute
  ClustersRoute: typeof ClustersRoute
  CommandsRoute: typeof CommandsRoute
  EventsRoute: typeof EventsRoute
  IpsRoute: typeof IpsRoute
  MlAnomaliesRoute: typeof MlAnomaliesRoute
  PayloadsRoute: typeof PayloadsRoute
  RecordingsRoute: typeof RecordingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-campaigns': {
      id: '/agent-campaigns'
      path: '/agent-campaigns'
      fullPath: '/agent-campaigns'
      preLoaderRoute: typeof AgentCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attackers': {
      id: '/attackers'
      path: '/attackers'
      fullPath: '/attackers'
      preLoaderRoute: typeof AttackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-events': {
      id: '/auth-events'
      path: '/auth-events'
      fullPath: '/auth-events'
      preLoaderRoute: typeof AuthEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ips': {
      id: '/ips'
      path: '/ips'
      fullPath: '/ips'
      preLoaderRoute: typeof IpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-anomalies': {
      id: '/ml-anomalies'
      path: '/ml-anomalies'
      fullPath: '/ml-anomalies'
      preLoaderRoute: typeof MlAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payloads': {
      id: '/payloads'
      path: '/payloads'
      fullPath: '/payloads'
      preLoaderRoute: typeof PayloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentCampaignsRoute: AgentCampaignsRoute,
  AlertsRoute: AlertsRoute,
  AttackersRoute: AttackersRoute,
  AuthEventsRoute: AuthEventsRoute,
  CampaignsRoute: CampaignsRoute,
  ClustersRoute: ClustersRoute,
  CommandsRoute: CommandsRoute,
  EventsRoute: EventsRoute,
  IpsRoute: IpsRoute,
  MlAnomaliesRoute: MlAnomaliesRoute,
  PayloadsRoute: PayloadsRoute,
  RecordingsRoute: RecordingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
