// Generated by analysis/yara/sync-yara.sh - do not edit.
// Local rules first; upstream/ is vendored and pinned in upstream.lock.
include "honeypot.yar"
include "upstream/auto/190460923_exe.yar"
include "upstream/auto/chatgpt_installer_exe.yar"
include "upstream/auto/cw6hi673_exe.yar"
include "upstream/auto/unknown_a9cfcd02.yar"
include "upstream/elf_malware.yar"
include "upstream/generic.yar"
include "upstream/malicious_docs.yar"
include "upstream/miori_mirai.yar"
include "upstream/pe_malware.yar"
include "upstream/scripts.yar"
