#!/usr/bin/env python3
"""Regression tests for #3403: the VPS IP-block sidecar fetched a URL that is
not a route, and could not tell it had failed.

`vps/portbridge-manual-blackhole-refresh.sh` defaulted
`MANUAL_BLACKHOLE_URL` to `/export/portbridge-manual-blackhole.txt`. Measured
live on the homeserver, that path answers 200 with a 0-byte body (an HTML
auth-redirect page), and the route that actually serves the export,
`/api/v1/ip-block-export`, answers 307 to `/auth/login?return_to=...` to an
unauthenticated caller. So `curl -fsSL` exited 0, the sidecar logged
"updated ... (0 addresses)", and every 300 seconds it replaced a working
`/blackhole/manual.txt` with nothing. Operator IP blocks never reached
portbridge and there was no signal anywhere that they had stopped.

The failure was silent for a specific, repeatable reason: the frontend answers
an *unknown path* with an auth redirect, so a 404-shaped mistake and a
200-shaped success were indistinguishable to `curl -f`. A missing route
returning 404 was always handled; the 200-with-0-bytes and the 307-to-login
were not, and those are the two the tests below drive.

What these tests pin:

* a 200 with a 0-byte body is refused, and the existing list survives
  byte-for-byte;
* a 307 to the login page is refused, and the existing list survives
  byte-for-byte (a redirect HTML page is not a blocklist -- that is the bug);
* a 404 is still refused the same way, so the one case that already worked
  keeps working;
* a real export is written, and the address count in the log matches the file;
* the request authenticates with the dashboard's existing service token, in
  the existing `X-Service-Token` header, handed to curl through its stdin
  config so the secret is never in argv, the process list, or the log -- and
  an unset token is a loud refusal rather than an unauthenticated attempt,
  because the unauthenticated answer IS the bug;
* nothing here is allowed to change the route: `openapi.json` is generated by
  utoipa and the export's contract (200 `text/plain`, 401, 502) is what the
  sidecar's checks are derived from. Notably the contract has no 3xx at all,
  which is why the sidecar does not follow redirects -- a 307 on the wire is
  an interception, never this route.

The behavioural half runs the real script against a real local HTTP server
with real curl, the same shape test_3283_fix.py established: the failure here
is a specific HTTP response body, and a stubbed `curl` cannot produce one.
"""
from __future__ import annotations

import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "vps/portbridge-manual-blackhole-refresh.sh"
COMPOSE = REPO_ROOT / "vps/docker-compose.yml"
VPS_ENV_EXAMPLE = REPO_ROOT / "vps/.env.example"
DESIGN_DOC = REPO_ROOT / "docs/dashboard-manual-ip-block-design.md"
BACKEND_IP_BLOCK = REPO_ROOT / "arcane/home/honeypot-dashboard/backend-service/src/ip_block.rs"
OPENAPI_JSON = REPO_ROOT / "arcane/home/honeypot-dashboard/backend-service/openapi.json"
TOKEN_ENV = "DASHBOARD_SERVICE_TOKEN"

# The route that actually serves the export, and the one that never existed.
REAL_ROUTE = "/api/v1/ip-block-export"
DEAD_PATH = "/export/portbridge-manual-blackhole.txt"

# What an operator's working list looks like before the sidecar runs. Any
# refusal must leave exactly this, byte for byte.
WORKING_LIST = "203.0.113.5\n203.0.113.6\n"
A_REAL_EXPORT = "192.0.2.10\n198.51.100.7\n"

# The dashboard's own answer to an unauthenticated request for the export
# route: 307, no body, and a Location that serves the login page. #3403 is
# this pair of responses seen in the wrong order.
LOGIN_PAGE = (
    b"<!doctype html>\n<html><head><title>Sign in</title></head>\n"
    b"<body><form action=\"/auth/login\" method=\"post\"></form></body></html>\n"
)

CURL = shutil.which("curl")
needs_curl = pytest.mark.skipif(CURL is None, reason="curl is not installed; the script under test is curl")
needs_sh = pytest.mark.skipif(shutil.which("sh") is None, reason="no /bin/sh; the script under test is POSIX sh")


# ------------------------------------------------- the response the test serves ----

# A real blocklist body must be accepted; anything else is what the sidecar
# is supposed to refuse. Enforced rather than documented: a mode string that
# does not match would fall through the handler to the "real export" branch,
# and every negative test below would then pass vacuously against a working
# sidecar.
MODES = ("export", "empty-200", "redirect-307", "html-200", "not-found-404")


class _ExportHandler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, *args):  # silence the default stderr spam
        pass

    def _respond(self, status: int, body: bytes, content_type: str, extra=()):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        for key, value in extra:
            self.send_header(key, value)
        self.end_headers()
        if body:
            self.wfile.write(body)

    def do_GET(self):  # noqa: N802 -- http.server's own name
        server = self.server
        server.requests.append({"path": self.path, "token": self.headers.get("X-Service-Token")})
        mode = server.mode
        if self.path.startswith("/auth/login"):
            self._respond(200, LOGIN_PAGE, "text/html; charset=utf-8")
        elif mode == "empty-200":
            # The measured #3403 shape: a success status, no body at all.
            self._respond(200, b"", "text/plain; charset=utf-8")
        elif mode == "redirect-307":
            self._respond(
                307,
                b"",
                "text/plain; charset=utf-8",
                extra=[("Location", "/auth/login?return_to=" + self.path)],
            )
        elif mode == "html-200":
            # A login page delivered as a plain 200 -- what a redirect-following
            # fetch ends up holding. The status gate cannot catch it; the
            # content-type and line-format gates exist for exactly this.
            self._respond(200, LOGIN_PAGE, "text/html; charset=utf-8")
        elif mode == "not-found-404":
            self._respond(404, b"not found", "text/plain; charset=utf-8")
        else:
            self._respond(200, server.export_body, "text/plain; charset=utf-8")


class _Server(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, mode: str):
        super().__init__(("127.0.0.1", 0), _ExportHandler)
        self.mode = mode
        self.export_body = A_REAL_EXPORT.encode()
        self.requests: list[dict] = []


@pytest.fixture
def export_server():
    """Yields a factory: `export_server("empty-200")` starts a server in that
    mode and tears it down afterwards. One server per test keeps the request
    log unambiguous about which case saw what."""
    servers = []

    def start(mode: str) -> _Server:
        assert mode in MODES, f"unknown response mode {mode!r}; a typo would fall through to a valid export"
        server = _Server(mode)
        threading.Thread(target=server.serve_forever, daemon=True).start()
        servers.append(server)
        return server

    yield start
    for server in servers:
        server.shutdown()
        server.server_close()


# ------------------------------------------------------ driving the real script ----

# The loop only ever reaches `updated ...` or a `[E-*]` refusal after it has
# decided what to do with the response, so this is the point at which the
# filesystem and the log both describe the same, settled, decision.
SETTLED = re.compile(r"portbridge-manual-blackhole-refresh: (updated |\[E-)")


def _run_sidecar(tmp_path: pathlib.Path, port: int, token: str | None, settle_timeout: float = 25.0):
    """Run the real script once against the local server and return
    (stderr, list contents, stray files in the list's directory).

    The script is a `while true` 5-minute loop, so the interval is set far
    past the test's patience and the process is stopped the moment the first
    iteration has made and announced its decision. That is the only race-free
    moment to inspect: before it, nothing has happened; after it, the next
    iteration is 3600s away."""
    blackhole = tmp_path / "blackhole"
    blackhole.mkdir(exist_ok=True)
    dest = blackhole / "manual.txt"
    dest.write_text(WORKING_LIST)

    env = dict(os.environ)
    env["MANUAL_BLACKHOLE_URL"] = f"http://127.0.0.1:{port}/bff{REAL_ROUTE}"
    env["BLACKHOLE_MANUAL_LIST"] = str(dest)
    env["MANUAL_REFRESH_INTERVAL_SECONDS"] = "3600"
    if token is None:
        env.pop(TOKEN_ENV, None)
    else:
        env[TOKEN_ENV] = token

    proc = subprocess.Popen(
        ["sh", str(SCRIPT)],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    try:
        lines: list[str] = []
        deadline = threading.Event()

        def drain():
            for line in proc.stderr:
                lines.append(line)
                if SETTLED.search(line):
                    deadline.set()

        reader = threading.Thread(target=drain, daemon=True)
        reader.start()
        assert deadline.wait(settle_timeout), (
            "the sidecar never announced a decision within "
            f"{settle_timeout}s; stderr so far: {''.join(lines)!r}"
        )
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:  # pragma: no cover -- only on a wedged sh
            proc.kill()
            proc.wait(timeout=10)
        reader.join(timeout=10)

    stderr = "".join(lines)
    stray = sorted(p.name for p in blackhole.iterdir() if p.name != "manual.txt")
    return stderr, dest.read_text(), stray


# ------------------------------------------------- 1. the response is not a list ----


@needs_sh
@needs_curl
def test_a_200_with_zero_bytes_is_refused_and_the_list_survives(tmp_path, export_server):
    """The measured #3403 failure. `curl -f` exits 0 on a 200, so this body
    was written to manual.txt every 300 seconds, emptying every operator
    block. A 0-byte export must be refused and the working list left alone."""
    server = export_server("empty-200")
    stderr, contents, stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == WORKING_LIST, (
        "a 200 with a 0-byte body truncated the blocklist (#3403). The export "
        f"must not be written; manual.txt is now {contents!r}"
    )
    assert "[E-" in stderr, (
        "an empty export must be refused loudly, not logged as an ordinary "
        f"refresh; stderr was: {stderr!r}"
    )
    assert "updated" not in stderr, (
        f"a refused body must never be reported as an update (#3403): {stderr!r}"
    )
    assert stray == [], f"a refusal must not leave temp files behind: {stray}"


@needs_sh
@needs_curl
def test_a_307_to_the_login_page_is_refused_and_the_list_survives(tmp_path, export_server):
    """The other measured #3403 failure, and the reason the old script could
    not see either one: `-fsSL` follows the 307 and writes the login page's
    HTML to manual.txt. portbridge.go then reads a file with no addresses in
    it. A redirect is not a blocklist, redirects are not followed, and the
    existing list survives."""
    server = export_server("redirect-307")
    stderr, contents, stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == WORKING_LIST, (
        "a 307 to /auth/login was written over the blocklist (#3403); manual.txt "
        f"is now {contents!r}"
    )
    assert "[E-" in stderr, f"a redirect must be refused loudly; stderr was: {stderr!r}"
    assert "307" in stderr, (
        "the refusal must name the status it got, so an operator can tell an "
        f"auth redirect from a moved route: {stderr!r}"
    )
    assert "updated" not in stderr, f"a refusal must not report an update: {stderr!r}"
    assert stray == [], f"a refusal must not leave temp files behind: {stray}"


@needs_sh
@needs_curl
def test_a_login_page_delivered_as_a_plain_200_is_still_refused(tmp_path, export_server):
    """The belt to the redirect gate's braces: the same login page arriving
    as a 200 (anything that already followed the redirect, or an intercepting
    proxy) must also be refused. The status gate cannot catch this one, which
    is why the content type and the line format are checked too."""
    server = export_server("html-200")
    stderr, contents, _stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == WORKING_LIST, (
        f"an HTML page was written over the blocklist (#3403): {contents!r}"
    )
    assert "[E-" in stderr, f"an HTML body must be refused loudly; stderr was: {stderr!r}"


@needs_sh
@needs_curl
def test_a_missing_route_returning_404_is_still_refused(tmp_path, export_server):
    """The one case that already worked. #3403 must not have cost it: a 404
    keeps the existing list and says so."""
    server = export_server("not-found-404")
    stderr, contents, _stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == WORKING_LIST, f"a 404 must keep the existing list; manual.txt is now {contents!r}"
    assert "[E-" in stderr, f"a 404 must be refused loudly; stderr was: {stderr!r}"
    assert "404" in stderr, f"the refusal must name the status: {stderr!r}"


@needs_sh
@needs_curl
def test_a_refused_export_leaves_no_temp_file_for_the_next_reader(tmp_path, export_server):
    """The atomic-rename contract is only real if the temp file is cleaned up:
    a leftover `manual.txt.tmp.<pid>` in the same directory is what a stale
    writer would look like to the next reader, and it grows one per interval
    on a permanently broken endpoint."""
    server = export_server("empty-200")
    _stderr, _contents, stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")
    assert stray == [], (
        f"a refused export left files behind in the list's directory: {stray} -- "
        "these accumulate one per interval on a permanently broken endpoint"
    )


# -------------------------------------------------------- 2. a real export works ----


@needs_sh
@needs_curl
def test_a_real_export_is_written_and_counted(tmp_path, export_server):
    """The fix must not have broken the feature. A 200 text/plain body of
    addresses replaces the list, and the count in the log is the number of
    addresses in the file -- never a number that came from somewhere else."""
    server = export_server("export")
    stderr, contents, stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == A_REAL_EXPORT, (
        f"a valid export was not written to the list (#3403); manual.txt is {contents!r}"
    )
    assert "updated" in stderr, f"a successful refresh must say so; stderr was: {stderr!r}"
    assert f"{len(A_REAL_EXPORT.splitlines())} addresses" in stderr, (
        "the logged address count must match the addresses written, or the log "
        f"lies about the list's contents: {stderr!r}"
    )
    assert stray == [], f"a successful rename must not leave a temp file: {stray}"


@needs_sh
@needs_curl
def test_comments_and_trailing_annotations_are_still_accepted(tmp_path, export_server):
    """blackhole.go's readOne accepts blank lines, '#' comments and
    mass_scanner.txt's "<ip> # host" annotation shape. A format check that
    rejected those would refuse a legitimate list and silently stop
    delivering operator blocks -- a new #3403 rather than the end of one."""
    annotated = "# operator blocks, exported by ip_block::export\n192.0.2.10 # first\n\n203.0.113.9\n"
    server = export_server("export")
    server.export_body = annotated.encode()

    stderr, contents, _stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == annotated, (
        "a body of comments, blanks and annotated addresses is in the format "
        f"blackhole.go reads and must be written verbatim; got {contents!r}"
    )
    assert "updated" in stderr, f"such a body must count as a successful refresh; stderr was: {stderr!r}"
    assert "2 addresses" in stderr, (
        "the count must be the addresses written, not the lines in the file: "
        f"{stderr!r}"
    )


# --------------------------------------------------- 3. the request authenticates ----


@needs_sh
@needs_curl
def test_an_ipv6_entry_is_delivered_not_refused(tmp_path, export_server):
    """ip_block::set_block parses an `IpAddr` and the export emits the stored
    string verbatim, so an IPv6 address is a legal line in this body, and
    blackhole.go's readOne consumes it (`net.ParseIP`). A format check that
    only understood dotted quads would refuse the WHOLE export over one IPv6
    entry -- which stops every operator block being delivered. That is #3403
    again wearing a fix's clothes, and it is the reason the check is written
    against what readOne accepts rather than against the sample list."""
    mixed = "192.0.2.10\n2001:db8::dead:beef\n"
    server = export_server("export")
    server.export_body = mixed.encode()

    stderr, contents, _stray = _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert contents == mixed, (
        "an export containing an IPv6 address must be delivered verbatim; "
        f"manual.txt is {contents!r} and stderr was {stderr!r}"
    )
    assert "updated" in stderr, f"an IPv6 entry must not fail the refresh: {stderr!r}"
    assert "2 addresses" in stderr, f"both addresses must be counted: {stderr!r}"


@needs_sh
@needs_curl
def test_the_export_is_requested_with_the_service_token_header(tmp_path, export_server):
    """`/api/v1/ip-block-export` is auth-gated (require_service_token, #2183;
    `security: [{serviceToken: []}]` in the generated openapi.json). The
    sidecar has to present the existing shared secret, in the existing
    header, or the dashboard answers 307 -- which is #3403 again."""
    server = export_server("export")
    _run_sidecar(tmp_path, server.server_address[1], "test-service-token")

    assert server.requests, "the sidecar never requested the export route"
    request = server.requests[0]
    assert REAL_ROUTE in request["path"], (
        f"the sidecar must request the real export route; it requested {request['path']!r} (#3403)"
    )
    assert request["token"] == "test-service-token", (
        "the export request must carry DASHBOARD_SERVICE_TOKEN in an "
        f"X-Service-Token header; the server saw {request['token']!r} (#3403)"
    )


@needs_sh
@needs_curl
def test_the_token_never_reaches_the_log(tmp_path, export_server):
    """The one hard rule about credentials: never in a log. A refusal message
    is the thing most likely to be pasted into a bug report, and a real
    deployment's token is a working credential for the whole service tier."""
    server = export_server("empty-200")
    stderr, _contents, _stray = _run_sidecar(tmp_path, server.server_address[1], "sup3r-s3cret-value")

    assert "sup3r-s3cret-value" not in stderr, (
        "the service token was written to the sidecar's stderr (#3403)"
    )
    assert "updated" not in stderr, "a refused export must not report an update: " + stderr


@needs_sh
@needs_curl
def test_an_unset_token_is_refused_without_making_the_request(tmp_path, export_server):
    """The trap. "Just try it unauthenticated" reproduces #3403 exactly: the
    dashboard answers 307, and the old script wrote the login page. An unset
    token must be a loud refusal, and no request may be made at all."""
    server = export_server("export")
    stderr, contents, _stray = _run_sidecar(tmp_path, server.server_address[1], token=None)

    assert server.requests == [], (
        "with no token the sidecar must not make the request (#3403): an "
        f"unauthenticated fetch of an auth-gated route answers 307; it made {server.requests!r}"
    )
    assert contents == WORKING_LIST, f"a refusal must keep the existing list; manual.txt is now {contents!r}"
    assert "[E-" in stderr, f"a missing token must be refused loudly; stderr was: {stderr!r}"
    assert TOKEN_ENV in stderr, (
        f"the refusal must name {TOKEN_ENV}, or the operator cannot act on it: {stderr!r}"
    )


@needs_sh
@needs_curl
def test_an_unreachable_homeserver_keeps_the_list(tmp_path, export_server):
    """The 5-minute loop has to survive the homeserver being briefly down.
    A transient failure must skip a refresh, not end the sidecar's usefulness
    by emptying the one file it exists to maintain."""
    # Started then immediately shut down: the port is bound and then free, so
    # this is a connect failure rather than a slow response.
    server = export_server("export")
    port = server.server_address[1]
    server.shutdown()
    server.server_close()

    stderr, contents, _stray = _run_sidecar(tmp_path, port, "test-service-token")
    assert contents == WORKING_LIST, f"a failed fetch must keep the existing list; manual.txt is {contents!r}"
    assert "[E-" in stderr, f"a failed fetch must be refused loudly; stderr was: {stderr!r}"


# ------------------------------------------------- 4. the configuration says so ----


def _script_text() -> str:
    return SCRIPT.read_text(encoding="utf-8")


def test_the_default_url_is_the_route_that_exists():
    """Fix 1. The default pointed at a path the dashboard does not serve; the
    export lives on `/api/v1/ip-block-export`, reached through the BFF's
    `/bff/*` proxy -- the same seam
    scripts/github-ci-runner/dashboard-source-health.sh already uses."""
    text = _script_text()
    default = re.search(r'MANUAL_BLACKHOLE_URL:-([^}"]+)', text)
    assert default, "the sidecar must keep MANUAL_BLACKHOLE_URL overridable"
    url = default.group(1)
    assert REAL_ROUTE in url, (
        f"the sidecar's default URL must be the route that serves the export, {REAL_ROUTE!r}; got {url!r} (#3403)"
    )
    assert DEAD_PATH not in url, (
        f"{DEAD_PATH} is not a route -- it answers 200 with a 0-byte auth-redirect page, which is #3403"
    )
    assert url.startswith("http://10.8.0.2:19090/"), (
        "the host and port must stay the dashboard's real published binding "
        f"(docs/CGNAT-DEPLOYMENT.md); got {url!r}"
    )


def test_compose_points_the_sidecar_at_the_same_route():
    """The URL in docker-compose.yml overrides the script's default, so a
    fixed default alone would change nothing on a deployed VPS."""
    text = COMPOSE.read_text(encoding="utf-8")
    service = text[text.index("  portbridge-manual-blackhole-refresh:") :]
    env = re.search(r"environment:\n((?:      - .*\n)+)", service)
    assert env, "the sidecar's environment block was not found in vps/docker-compose.yml"
    entries = env.group(1)
    url = next((ln for ln in entries.splitlines() if "MANUAL_BLACKHOLE_URL=" in ln), None)
    assert url, "docker-compose.yml no longer sets MANUAL_BLACKHOLE_URL for the sidecar"
    assert REAL_ROUTE in url, (
        f"docker-compose.yml overrides the script's default, so it must carry the real route too; got {url!r} (#3403)"
    )
    assert DEAD_PATH not in text, (
        f"{DEAD_PATH} is still configured somewhere in vps/docker-compose.yml (#3403)"
    )


def _script_code() -> str:
    """The script with comments stripped and line continuations joined, so an
    assertion about an invocation cannot be satisfied by prose about it (the
    header deliberately names the old `curl -fsSL` to explain #3403)."""
    body = "\n".join(ln for ln in _script_text().splitlines() if not ln.lstrip().startswith("#"))
    return body.replace("\\\n", " ")


def test_redirects_are_not_followed():
    """`-L` is why the 307 was invisible: curl followed it to the login page
    and reported 200. The export's own contract (openapi.json) has no 3xx at
    all, so any redirect on the wire is an interception, not this route."""
    code = _script_code()
    invocation = next((seg for seg in code.split("curl ") if "--max-time" in seg.split('"')[0]), None)
    assert invocation, "the fetch's curl invocation was not found in the script"
    flags = invocation.split('"')[0]
    assert "-L" not in flags.split(), (
        "the fetch must not follow redirects -- that is how a 307 became an "
        f"invisible 200 (#3403): flags were {flags.split()!r}"
    )
    assert "-f" not in flags.split(), (
        "`-f` is what made a 404 the only failure this script could see; the "
        "status is now checked explicitly so a refusal can name it (#3403)"
    )
    assert "-fsSL" not in code, "the old -fsSL invocation is still here (#3403)"


def test_the_token_is_handed_to_curl_out_of_argv():
    """The repo's own rule for this, from
    scripts/github-ci-runner/dashboard-source-health.sh: "the token is not
    visible in the process list while the request runs." `-H "X-Service-Token:
    $token"` puts it in argv; curl's stdin config (`-K -`) does not."""
    code = _script_code()
    assert 'header = "X-Service-Token: %s"' in code, (
        "the service token must be passed as an X-Service-Token header (#3403)"
    )
    assert "-K -" in code, (
        "the token must reach curl through its stdin config (-K -) so it is "
        "never in argv or the container's process list, the same way "
        "dashboard-source-health.sh does it"
    )
    assert not re.search(r"-H\s+[\"']?X-Service-Token", code), (
        "an -H flag would put the service token in the process list"
    )


def test_no_credential_is_committed_anywhere_it_touches():
    """No hardcoded token, and the .env.example entry ships empty. A literal
    here would be a live credential for the whole service tier, in a public
    repository, forever. Compose's own `${DASHBOARD_SERVICE_TOKEN:-}` is the
    interpolation, not a literal, and is the only shape allowed."""
    for path, text in ((SCRIPT, _script_text()), (COMPOSE, COMPOSE.read_text(encoding="utf-8"))):
        assert not re.search(rf"{TOKEN_ENV}\s*=\s*(?!\$\{{|\$)\S", text), (
            f"{path.name} assigns a literal value to {TOKEN_ENV}; it must be an "
            "operator-supplied environment value, interpolated or empty"
        )
    example = VPS_ENV_EXAMPLE.read_text(encoding="utf-8")
    assert f"{TOKEN_ENV}=\n" in example, (
        f"vps/.env.example must document {TOKEN_ENV} with an empty value, the way every other secret here is documented"
    )
    assert DEAD_PATH not in example


def test_the_env_example_names_the_one_token_in_the_fleet():
    """There is exactly one service token in this deployment, already named
    DASHBOARD_SERVICE_TOKEN by the home stack. The VPS must reuse that name
    and value, not introduce a second mechanism for the puller to
    authenticate with -- the design question #3403 actually turned on."""
    example = VPS_ENV_EXAMPLE.read_text(encoding="utf-8")
    section = example[example.index("DASHBOARD_SERVICE_TOKEN") :]
    assert "SERVICE_TOKEN" in section, "the entry must say this is the same secret the home stack carries as SERVICE_TOKEN"
    assert TOKEN_ENV in section
    assert "chmod 600" in example or "600" in section, (
        "the entry must record that the file holding the token is 600 and never in the repository"
    )


# ------------------------------------------- 5. the route itself is not changed ----


def test_the_export_routes_own_contract_is_unchanged():
    """The sidecar's checks are derived from the route's generated contract,
    so that contract is load-bearing: 200 carries `text/plain` (which is why
    the content-type gate is written the way it is) and there is no 3xx (which
    is why redirects are not followed). #3403 changed the caller; it must not
    have changed the route, its status codes, or its behaviour.

    openapi.json is GENERATED by utoipa (#3382) -- regenerate with
    `cargo run --bin openapi`, never hand-edit. Reading it here is how a
    hand-edit that changed a status code would be caught."""
    spec = json.loads(OPENAPI_JSON.read_text(encoding="utf-8"))
    responses = spec["paths"][REAL_ROUTE]["get"]["responses"]
    assert set(responses) == {"200", "401", "502"}, (
        f"the export route's status codes changed; #3403 must not touch them. Got {sorted(responses)}"
    )
    assert "text/plain" in responses["200"]["content"], (
        "the export's 200 must stay text/plain -- the sidecar's content-type "
        f"gate is written against it. Got {sorted(responses['200']['content'])}"
    )
    assert not [code for code in responses if code.startswith("3")], (
        "the export route declares a 3xx; there is no legitimate redirect here, "
        "and the sidecar's do-not-follow decision is derived from that"
    )
    assert spec["paths"][REAL_ROUTE]["get"]["security"] == [{"serviceToken": []}], (
        "the export must stay service-token gated -- the sidecar authenticates "
        "because of this, and it is the reason an unauthenticated fetch 307s"
    )


def test_the_route_handler_still_refuses_an_es_outage_rather_than_exporting_nothing():
    """`ip_block::export`'s own #1342 guarantee: an Elasticsearch failure is a
    502, never an empty 200. This is the upstream half of #3403 -- a 502 is
    correctly refused by the sidecar's status gate, and must stay a 502 rather
    than being softened into a 200 with no addresses in it, which is the exact
    shape the sidecar now has to defend against."""
    text = BACKEND_IP_BLOCK.read_text(encoding="utf-8")
    export_fn = text[text.index("pub async fn export(") :]
    assert "BAD_GATEWAY" in export_fn, (
        "ip_block::export must keep mapping an ES failure to 502; an empty 200 "
        "here is what the sidecar cannot distinguish from a broken fetch (#3403)"
    )
    assert "(status = 200" in text and "(status = 502" in text, (
        "the utoipa response list for the ip-block routes lost a status code; "
        "regenerate with `cargo run --bin openapi`, never hand-edit"
    )


def test_the_design_record_covers_the_correction():
    """Decision 4 is what vps/docker-compose.yml and the sidecar's own header
    both cite, and it still asserted the pre-#3403 auth posture and the
    "no minimum-count sanity floor" rule. Shipping code that cites a decision
    the code no longer follows is how the next reader reinstates the bug."""
    doc = DESIGN_DOC.read_text(encoding="utf-8")
    section = doc[doc.index("## Decision 4") :]
    assert "3403" in section, (
        "docs/dashboard-manual-ip-block-design.md's decision 4 must record "
        "#3403 -- both vps/docker-compose.yml and the sidecar's header cite it"
    )
    assert REAL_ROUTE in section, "decision 4 must name the route the puller actually fetches"
    assert TOKEN_ENV in section, (
        f"decision 4 must record that the puller authenticates with {TOKEN_ENV} -- the auth posture it cited is no longer true"
    )
    assert "/auth/login" in section, "decision 4 must record the 307-to-login shape that hid the failure"


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
