#!/usr/bin/env python3
"""Fail a pull request that carries AI/assistant attribution (#3329).

Repository policy: commits, PR titles/bodies and issue text never credit an
AI assistant -- no assistant Co-authored-by trailers, no "Generated with ..."
footers, no assistant session links. It was enforced by convention only, and
the convention did not hold: between 2026-08-01 and 2026-09-26 main collected
hundreds of `Co-authored-by: Claude ... <noreply@anthropic.com>` trailers and
`Claude-Session:` links from automated sessions. Squash merges copy every
commit's trailers into the landed commit, so checking the PR's own commits
plus its title and body catches it before it reaches main.

What counts is deliberately narrow -- attribution *shapes*, not mentions.
Prose that talks about an assistant or an LLM product (an issue about the
Claude API, the theme's "claude" palette) must pass. Matched:

- a Co-authored-by trailer whose name or address is an AI assistant;
- any *@anthropic.com / *@openai.com noreply address;
- assistant session trailers or links (Claude-Session:, claude.ai/code/session_);
- "Generated with/by <coding assistant>" footers, with or without the robot emoji.

In CI it reads the PR from $GITHUB_EVENT_PATH and its commits from the REST
API (no deep fetch, and no PR text ever passes through a shell). Dependabot
PRs are exempt: their bodies are machine-written by GitHub itself.

Usage:
  check-ai-attribution.py                      # CI: $GITHUB_EVENT_PATH + $GITHUB_TOKEN
  check-ai-attribution.py --text FILE [...]    # check files (or - for stdin)
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.request

# Co-author trailers: any assistant or model family -- nobody legitimately
# co-authors a commit with a model.
ASSISTANTS = r"(?:claude|anthropic|openai|chatgpt|gpt-?\d|codex|copilot|gemini|bard|kimi|moonshot|deepseek|qwen|cursor|devin|windsurf|codeium|tabnine|aider|sourcegraph cody)"

# Footers: coding assistants only. This repository benchmarks LLMs, so
# "summary generated by qwen3:14b" in a PR body is a result, not attribution.
CODING_ASSISTANTS = r"(?:claude(?:\s+code)?|codex|copilot|cursor|chatgpt|devin|windsurf|aider|kimi\s+code)\b"

RULES: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "assistant co-author trailer",
        re.compile(rf"^\s*co-authored-by:.*\b{ASSISTANTS}\b", re.IGNORECASE | re.MULTILINE),
    ),
    (
        "assistant noreply address",
        re.compile(r"\b[\w.+-]+@(?:[\w-]+\.)*(?:anthropic|openai)\.com\b", re.IGNORECASE),
    ),
    (
        "assistant session trailer",
        re.compile(r"^\s*(?:claude|codex|copilot|cursor)-session:", re.IGNORECASE | re.MULTILINE),
    ),
    (
        "assistant session link",
        re.compile(r"\bclaude\.ai/code/session_|\bchatgpt\.com/codex/tasks/", re.IGNORECASE),
    ),
    (
        "generated-with footer",
        re.compile(rf"(?:🤖\s*)?\bgenerated\s+(?:with|by)\s+\[?\s*{CODING_ASSISTANTS}", re.IGNORECASE),
    ),
)


def findings(text: str) -> list[str]:
    """Return 'rule: matched line' for every attribution in text."""
    hits = []
    for rule, pattern in RULES:
        for match in pattern.finditer(text):
            start = text.rfind("\n", 0, match.start()) + 1
            end = text.find("\n", match.end())
            line = text[start : end if end != -1 else len(text)].strip()
            hits.append(f"{rule}: {line[:200]}")
    return hits


def _api(url: str, token: str) -> object:
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310 -- fixed GitHub API host
        return json.load(resp)


def check_pull_request(event: dict, token: str, api: str) -> dict[str, list[str]]:
    pr = event["pull_request"]
    report: dict[str, list[str]] = {}
    for label, text in (("PR title", pr.get("title") or ""), ("PR body", pr.get("body") or "")):
        if hits := findings(text):
            report[label] = hits
    repo = event["repository"]["full_name"]
    page = 1
    while True:
        commits = _api(f"{api}/repos/{repo}/pulls/{pr['number']}/commits?per_page=100&page={page}", token)
        for commit in commits:
            if hits := findings(commit["commit"]["message"]):
                report[f"commit {commit['sha'][:10]}"] = hits
        if len(commits) < 100:
            return report
        page += 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--text", nargs="+", metavar="FILE", help="check these files ('-' = stdin) instead of a PR")
    args = parser.parse_args(argv)

    if args.text:
        report = {}
        for name in args.text:
            if name == "-":
                text = sys.stdin.read()
            else:
                with open(name, encoding="utf-8") as fh:
                    text = fh.read()
            if hits := findings(text):
                report[name] = hits
    else:
        event_path = os.environ.get("GITHUB_EVENT_PATH")
        if not event_path:
            print("no --text given and GITHUB_EVENT_PATH is unset", file=sys.stderr)
            return 2
        with open(event_path, encoding="utf-8") as fh:
            event = json.load(fh)
        if "pull_request" not in event:
            print("not a pull_request event -- nothing to check")
            return 0
        if event["pull_request"]["user"]["login"] == "dependabot[bot]":
            print("dependabot PR -- exempt")
            return 0
        report = check_pull_request(event, os.environ["GITHUB_TOKEN"], os.environ.get("GITHUB_API_URL", "https://api.github.com"))

    if not report:
        print("no AI/assistant attribution found")
        return 0
    print("AI/assistant attribution is not allowed in this repository (#3329). Remove it and force-push or edit:")
    for where, hits in report.items():
        for hit in hits:
            print(f"  {where}: {hit}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
